export type productType = {
  [key: string]: {
    name: string;
    url: string;
    price?: number;
    category?: string;
    subCategory?: string;
    description?: string;
    brand?: string;
    isGifting?: boolean;
    desc?: {
      packaging?: string; // Packaging
      noOfPkt?: string | number; // Allow both string and number
      noOfUnits?: number; // Number of units
      mrp?: number; // MRP
      netWeight?: number; // Number of units
    };
  }[];
};

const descriptionObj = {
  // ₹5/- WAFER STICKS
  "DAIRY KISS1": { packaging: "Box", noOfPkt: 24, noOfUnits: 24, mrp: 240 },
  "BIG WOFFO ROLL": { packaging: "Box", noOfPkt: 12, noOfUnits: 10, mrp: 300 },
  "BIG ROLLE CHOC": { packaging: "Box", noOfPkt: 24, noOfUnits: 30, mrp: 150 },
  "ROLLE STIX": { packaging: "Jar", noOfPkt: 20, noOfUnits: 32, mrp: 160 },
  "3 STIX CHOCO": { packaging: "Box", noOfPkt: 20, noOfUnits: 32, mrp: 160 },
  // added last ones //
    "COcos Pouch": {
    packaging: "Pouch",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "TRUFFLE POUCH1": {
    packaging: "Pouch",
    noOfPkt: 12,
    noOfUnits: 70,
    mrp: 350,
  },
  "EMPORIO POUCH": {
    packaging: "Pouch",
    noOfPkt: 12,
    noOfUnits: 70,
    mrp: 350,
  },
    "Truffins Cont": {
    packaging: "Cont",
    noOfPkt: 12,
    noOfUnits: 70,
    mrp: 350,
  },
  "CHOCO TOCO": {
    packaging: "Pouch",
    noOfPkt: 18,
    noOfUnits: 24,
    mrp: 240,
  },
  "CHOC CONE": {
    packaging: "Jar",
    noOfPkt: 30,
    noOfUnits: 30,
    mrp: 150,
  },
  "OH WOW BIG": {
    packaging: "Box",
    noOfPkt: 12,
    noOfUnits: 125,
    mrp: 250,
  },
  "OH WOW CENTERSEAL POUCH": {
    packaging: "Pouch",
    noOfPkt: 12,
    noOfUnits: 100,
    mrp: 200,
  },
  "OH WOW GIFT BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "OH WOW STANDEE POUCH": {
    packaging: "Pouch",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 100,
  },
  // ₹5/- PREMIUM GIFT PACK
  "GLORIOUS HEART": {
    packaging: "Cont",
    noOfPkt: 20,
    noOfUnits: 240,
    mrp: 185,
  },
    "TRuffle OCtagon": {
    packaging: "Cont",
    noOfPkt: 12,
    netWeight: 240,
    mrp: 200,
  },
     "Stacy MIni COnt": {
    packaging: "Cont",
    noOfPkt: 30,
    netWeight: 180,
    mrp: 150,
  },
       "BOlivia MIni COnt": {
    packaging: "Cont",
    noOfPkt: 16,
    netWeight: 360,
    mrp: 250,
  },
    "TRuffle OCtagon heart": {
    packaging: "Cont",
    noOfPkt: 12,
    netWeight: 300,
    mrp: 240,
  },
  "TRUFFLE HEART": { packaging: "Cont", noOfPkt: 12, noOfUnits: 240, mrp: 185 },
  "TRUFFLE OCTAGON": {
    packaging: "Cont",
    noOfPkt: 12,
    noOfUnits: 300,
    mrp: 220,
  },
    "BOlivia gift box": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 25,
    mrp: 175,
  },
  "BOLIVIA CONT": { packaging: "Cont", noOfPkt: 16, noOfUnits: 360, mrp: 230 },

  // ₹5/- PREMIUM CHOCOLATE
  FEROLA: { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  GLORIOUS: { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "GLORIOUS CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "D'LOVE MIX": { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "D'LOVE GOLD": { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "D'LOVE RED": { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "D'LOVE MIX CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "D'LOVE GOLD CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "D'LOVE MIX JAR": { packaging: "Jar", noOfPkt: 24, noOfUnits: 40, mrp: 200 },
  "Truffle Container 70": {
    packaging: "Cont",
    noOfPkt: 12,
    noOfUnits: 70,
    mrp: 350,
  },
  "D'LOVE GOLD JAR": { packaging: "Jar", noOfPkt: 24, noOfUnits: 40, mrp: 200 },
  "D'LOVE MIX POUCH": {
    packaging: "Pouch",
    noOfPkt: 12,
    noOfUnits: 60,
    mrp: 0,
  },
  "D'LOVE GOLD POUCH": {
    packaging: "Pouch",
    noOfPkt: 12,
    noOfUnits: 60,
    mrp: 350,
  },
  "Cocotana Changed": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },

  EMPORIO: { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "EMPORIO CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  DELITE: { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "DELITE CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  TRUFFLE: { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "TRUFFLE SMALL": { packaging: "Box", noOfPkt: 35, noOfUnits: 20, mrp: 125 },
  "TRUFFLE CONTAINER": {
    packaging: "Cont",
    noOfPkt: 16,
    noOfUnits: 40,
    mrp: 200,
  },
  "TRUFFLE CONTAINER (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
    "Truffins Box 3opcs": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  BOLIVIA: { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "TRUFFLE POUCH": { packaging: "POuch", noOfPkt: 16, noOfUnits: 70, mrp: 350 }, ///grams
  "BOLIVIA SMALL": { packaging: "Box", noOfPkt: 24, noOfUnits: 25, mrp: 175 },
  "BOLIVIA CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  STACY: { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "STACY SMALL": { packaging: "Box", noOfPkt: 35, noOfUnits: 20, mrp: 125 },
  "STACY CONT": { packaging: "Cont", noOfPkt: 12, noOfUnits: 70, mrp: 350 },

  "BIG TRUFFLE": { packaging: "Box", noOfPkt: 6 }, // 2 kg no number of units 2 kg
  "BIG BOLIVIA": { packaging: "Box", noOfPkt: 6 },
  "BIG GLORIOUS": { packaging: "Box", noOfPkt: 6 },
  "BIG D'LOVE": { packaging: "Box", noOfPkt: 6 },
  "BIG DELITE": { packaging: "Box", noOfPkt: 6 },

  "KING KONG": { packaging: "Box", noOfPkt: 20, noOfUnits: 40, mrp: 200 },
  "DR. TEDDY": { packaging: "Box", noOfPkt: 20, noOfUnits: 40, mrp: 200 },
  // ₹5/- DECORATIVE CHOCOLATE
  "BIG STAR": { packaging: "Box", noOfPkt: 24, noOfUnits: 40, mrp: 200 },
  CHOKERS: { packaging: "Box", noOfPkt: 24, noOfUnits: 40, mrp: 200 },
  TORNUTTE: { packaging: "Box", noOfPkt: 24, noOfUnits: 40, mrp: 200 },
  CARANUT: { packaging: "Box", noOfPkt: 24, noOfUnits: 40, mrp: 200 },
  "BIG STAR CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "CHOKERS CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "TORNUTTE CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "CARANUT CONT (30 PCS)": {
    packaging: "Cont",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },

  // ₹5/- CHOCOLATE BAR
  "DAIRY KISS BLUE CONT (30 PCS)": {
    packaging: "Container",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "DAIRY KISS BLUE": { packaging: "Box", noOfPkt: 24, noOfUnits: 30, mrp: 150 },
  "DAIRY KISS GOLD": { packaging: "Box", noOfPkt: 24, noOfUnits: 30, mrp: 150 },
  "STACY BOX": { packaging: "Box", noOfPkt: 12, noOfUnits: 70, mrp: 350 },
  "DAIRY KISS BLACK & WHITE": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "DAIRY KISS STRAWBERRY": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "DAIRY KISS COCONUT": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "DAIRY KISS HAZELNUT": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },
  "DAIRY KISS RED": { packaging: "Box", noOfPkt: 24, noOfUnits: 30, mrp: 150 },
  "DAIRY KISS WHITE MILK": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 30,
    mrp: 150,
  },

  // ₹2/- PEANUT CHIKKI
  "OH! WOW BOX": { packaging: "Box", noOfPkt: 12, noOfUnits: 125, mrp: 250 },
  "OH! WOW CONT": { packaging: "Cont", noOfPkt: 12, noOfUnits: 100, mrp: 200 },

  // ₹2/- PREMIUM CHOCOLATE
  ENDON: { packaging: "Box", noOfPkt: 12, noOfUnits: "120 + 5", mrp: 300 },
  "ENDON SMALL BOX": { packaging: "Box", noOfPkt: 24, noOfUnits: 60, mrp: 150 },
  "DÉ GOLD": { packaging: "Box", noOfPkt: 12, noOfUnits: 125, mrp: 300 },
  "DÉ GOLD SMALL BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 60,
    mrp: 150,
  },
  "STACY MINI'S BOX": {
    packaging: "Box",
    noOfPkt: 12,
    noOfUnits: 125,
    mrp: 300,
  },
  "D-BON Coconut Jar": {
    packaging: "Jar",
    noOfPkt: 9,
    noOfUnits: 250,
    mrp: 250,
  },
  "Double Mango Jar": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 210,
    mrp: 210,
  },
  "STACY MINI'S MATKA JAR": {
    packaging: "Jar",
    noOfPkt: 8,
    noOfUnits: 120,
    mrp: 300,
  },
  "STACY MINI'S SMALL BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "STACY MINI'S CONTAINER": {
    packaging: "Cont",
    noOfPkt: 12,
    noOfUnits: 100,
    mrp: 200,
  },
  BREVO: { packaging: "Box", noOfPkt: 12, noOfUnits: 125, mrp: 300 },
  "BREVO SMALL BOX": { packaging: "Box", noOfPkt: 24, noOfUnits: 50, mrp: 125 },
  "BREVO CONTAINER": {
    packaging: "Cont",
    noOfPkt: 12,
    noOfUnits: 100,
    mrp: 250,
  },
  "UNITED JAR": { packaging: "Jar", noOfPkt: 12, noOfUnits: 125, mrp: 250 },
  "UNITED SMALL BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "DAIRY KISS": { packaging: "Box", noOfPkt: 24, noOfUnits: 80, mrp: 160 },
  "GOLD BOX": { packaging: "Box", noOfPkt: 24, noOfUnits: 50, mrp: 125 },
  "GOLD JAR": { packaging: "Jar", noOfPkt: 12, noOfUnits: 125, mrp: 250 },
  "SAFARI PARK": { packaging: "Cont", noOfPkt: 16, noOfUnits: 100, mrp: 200 },

  // ₹1/- CHOCOLATE
  "BLISS CHOCO": { packaging: "Box", noOfPkt: 24, noOfUnits: 125, mrp: 125 },
  "BLISS DARK": { packaging: "Box", noOfPkt: 24, noOfUnits: 125, mrp: 125 },
  "BLISS STRAWBERRY": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 125,
    mrp: 125,
  },

  // ₹1/- JELLY
  "JELLOS JAR": { packaging: "Jar", noOfPkt: 16, noOfUnits: 150, mrp: 150 },
  "JELLOS BOX": { packaging: "Box", noOfPkt: 30, noOfUnits: 80, mrp: 80 },

  // ₹5/- LOLLIPOP
  "FRUGO POP JAR": { packaging: "Jar", noOfPkt: 12, noOfUnits: 100, mrp: 500 },
  "FRUGO POP STAND": {
    packaging: "Stand",
    noOfPkt: 12,
    noOfUnits: 60,
    mrp: 300,
  },
  "FRUGO POP POUCH": {
    packaging: "Pouch",
    noOfPkt: 18,
    noOfUnits: 80,
    mrp: 400,
  },
  "FRUDOZA CONT": { packaging: "Cont", noOfPkt: 12, noOfUnits: 60, mrp: 300 },

  // ₹2/- LOLLIPOP
  "FRUTOS POP JAR": { packaging: "Jar", noOfPkt: 12, noOfUnits: 100, mrp: 200 },
  "LOLLY CONT": { packaging: "Cont", noOfPkt: 6, noOfUnits: 120, mrp: 240 },
  "TAMMY POP CONT": { packaging: "Cont", noOfPkt: 6, noOfUnits: 120, mrp: 240 },
  "LOLLY POUCH": { packaging: "Pouch", noOfPkt: 18, noOfUnits: 100, mrp: 200 },
  // ₹1/- HEART CENTERFILL CANDY
  "KISSZONE 50 PCS SMALL": {
    packaging: "Standy",
    noOfPkt: 40,
    noOfUnits: 50,
    mrp: 50,
  },
  "KISSZONE ASSORTED": {
    packaging: "Pouch",
    noOfPkt: 20,
    noOfUnits: 167,
    mrp: 167,
  },
  "KISSZONE DARK": {
    packaging: "Pouch",
    noOfPkt: 20,
    noOfUnits: 167,
    mrp: 167,
  },
  "KISSZONE STRAWBERRY": {
    packaging: "Pouch",
    noOfPkt: 20,
    noOfUnits: 167,
    mrp: 167,
  },
  "BEATING HEART": {
    packaging: "Pouch",
    noOfPkt: 20,
    noOfUnits: 167,
    mrp: 167,
  },
  "PAN MEETHA": { packaging: "Pouch", noOfPkt: 20, noOfUnits: 167, mrp: 167 },
  TAMBLEY: { packaging: "Pouch", noOfPkt: 20, noOfUnits: 167, mrp: 167 },
    "Endon Containerss": {
    packaging: "Cont",
    noOfPkt: 18,
    noOfUnits: 40,
    mrp: 200,
  },
  // ₹1/- CENTERFILL CANDY
  "DOUBLE STRAWBERRY": {
    packaging: "Pouch",
    noOfPkt: 20,
    noOfUnits: 150,
    mrp: 150,
  },
  "DOUBLE COCONUT": {
    packaging: "Pouch",
    noOfPkt: 20,
    noOfUnits: 150,
    mrp: 150,
  },
  "DOUBLE GUAVA": { packaging: "Pouch", noOfPkt: 20, noOfUnits: 150, mrp: 150 },
  "DOUBLE MANGO": { packaging: "Pouch", noOfPkt: 20, noOfUnits: 150, mrp: 150 },
  "CHOCO ORANGE": { packaging: "Pouch", noOfPkt: 20, noOfUnits: 150, mrp: 150 },
  "DOUBLE PAAN": { packaging: "Pouch", noOfPkt: 20, noOfUnits: 150, mrp: 150 },
  "DOUBLE KACCHA AAM": {
    packaging: "Pouch",
    noOfPkt: 20,
    noOfUnits: 150,
    mrp: 150,
  },
  "CHOCO CRUNCHY": { packaging: "Jar", noOfPkt: 12, noOfUnits: 200, mrp: 200 },
  "SPICY CRASH AAM": {
    packaging: "Jar",
    noOfPkt: 16,
    noOfUnits: 150,
    mrp: 150,
  },

  // ₹0.50/- CANDY
  "LONDON COW": { packaging: "Pouch", noOfPkt: 40, noOfUnits: 100, mrp: 50 },
  ORANJA: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 100, mrp: 50 },
  "KACCHE AAM": { packaging: "Pouch", noOfPkt: 40, noOfUnits: 100, mrp: 50 },
  FRUITO: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 100, mrp: 50 },
  GUAVA: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 150, mrp: 75 },
  ORANGE: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 160, mrp: 80 },
  MANGO: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 160, mrp: 80 },
  STRAWBERRY: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 160, mrp: 80 },
  PINEAPPLE: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 160, mrp: 80 },
  IMLI: { packaging: "Pouch", noOfPkt: 40, noOfUnits: 160, mrp: 80 },
  "KACHA AAM": { packaging: "Pouch", noOfPkt: 40, noOfUnits: 160, mrp: 80 },

  // ₹2/- PREMIUM TOFFEE
  "KESAR & KAJU KULFI": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 125,
    mrp: 250,
  },
  "COCONUT KULFI": { packaging: "Jar", noOfPkt: 12, noOfUnits: 125, mrp: 250 },
  "MALAI KULFI": { packaging: "Jar", noOfPkt: 12, noOfUnits: 125, mrp: 250 },
  SOFFITI: { packaging: "Jar", noOfPkt: 12, noOfUnits: 125, mrp: 250 },
  "GOA ALMOND": { packaging: "Jar", noOfPkt: 24, noOfUnits: 50, mrp: 150 },
  "GOA KAJU": { packaging: "Jar", noOfPkt: 24, noOfUnits: 50, mrp: 150 },

  // ₹2/- ECLAIRS TOFFEE
  "ECLAIRS DARK POUCH": {
    packaging: "Standy",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 250,
  },
  "ECLAIRS MILK POUCH": {
    packaging: "Standy",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 250,
  },
  "ECLAIRS HAZELNUT POUCH": {
    packaging: "Standy",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 250,
  },
  "ECLAIRS ANJEER POUCH": {
    packaging: "Standy",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 250,
  },
  "ECLAIRS COCONUT POUCH": {
    packaging: "Standy",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 250,
  },
  "COCOTANA POUCH": {
    packaging: "Standy",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 250,
  },
  "SELECTIONS POUCH": {
    packaging: "Standy",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 250,
  },
  "ECLAIRS DARK BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "ECLAIRS MILK BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "ECLAIRS HAZELNUT BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "ECLAIRS ANJEER BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "ECLAIRS COCONUT BOX": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 50,
    mrp: 125,
  },
  "COCOTANA BOX": { packaging: "Box", noOfPkt: 24, noOfUnits: 50, mrp: 125 },
  "SELECTIONS BOX": { packaging: "Box", noOfPkt: 24, noOfUnits: 50, mrp: 125 },

  // ₹2/- TOFFEE CONTAINER
  "HONEY CARAMEL": { packaging: "Cont", noOfPkt: 18, noOfUnits: 60, mrp: 150 },
  "CHOCO ALMOND": { packaging: "Cont", noOfPkt: 18, noOfUnits: 60, mrp: 150 },
  TREASURE: { packaging: "Cont", noOfPkt: 18, noOfUnits: 60, mrp: 150 },
  "PISTA HARVEST": { packaging: "Cont", noOfPkt: 18, noOfUnits: 60, mrp: 150 },
  COCOTANA: { packaging: "Cont", noOfPkt: 18, noOfUnits: 60, mrp: 150 },
  SELECTIONS: { packaging: "Cont", noOfPkt: 18, noOfUnits: 60, mrp: 150 },

  // ₹1/- TATTOO ECLAIRS TOFFEE
  "BLUE ÉCLAIR POUCH": {
    packaging: "Pouch",
    noOfPkt: 32,
    noOfUnits: 100,
    mrp: 100,
  },
  "RED ÉCLAIR POUCH": {
    packaging: "Pouch",
    noOfPkt: 32,
    noOfUnits: 100,
    mrp: 100,
  },
  "GOLD ÉCLAIR POUCH": {
    packaging: "Pouch",
    noOfPkt: 32,
    noOfUnits: 100,
    mrp: 100,
  },
  "WHITE ÉCLAIR POUCH": {
    packaging: "Pouch",
    noOfPkt: 32,
    noOfUnits: 100,
    mrp: 100,
  },
  "BLUE ÉCLAIR JAR": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 220,
    mrp: 220,
  },
  "RED ÉCLAIR JAR": { packaging: "Jar", noOfPkt: 12, noOfUnits: 220, mrp: 220 },
  "GOLD ÉCLAIR JAR": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 220,
    mrp: 220,
  },
  "WHITE ÉCLAIR JAR": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 220,
    mrp: 220,
  },

  // ₹1/- TOFFEE JAR
  "ÉCLAIR GOLD JAR": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 200,
    mrp: 200,
  },
  "KAJU BUTTER JAR": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 200,
    mrp: 200,
  },
  "PISTA BUTTER JAR": {
    packaging: "Jar",
    noOfPkt: 12,
    noOfUnits: 200,
    mrp: 200,
  },
  "NATURAL JAR": { packaging: "Jar", noOfPkt: 12, noOfUnits: 200, mrp: 200 },

  // ₹1/- TOFFEE BOX (HUT STYLE)
  "ÉCLAIR GOLD": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  ANJEER: { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "KAJU BUTTER": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "PISTA BUTTER": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "COCONUT BUTTER": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "ALMOND GOLD": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "RED ÉCLAIR": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "DAIRY WAY": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  COCOVILLE: { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "KASATA CREAM": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "BUTTER FEAST": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "NATURAL ORGANIC": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 100,
  },
  "JEWEL DRY FRUIT": {
    packaging: "Box",
    noOfPkt: 24,
    noOfUnits: 100,
    mrp: 100,
  },
  "KESAR CREAM": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "BUTTER SCOTCH": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "SWISS DAIRY": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },
  "PAN TOFFEE": { packaging: "Box", noOfPkt: 24, noOfUnits: 100, mrp: 100 },

  // ₹0.50/- TOFFEE POUCH
  "COFFEE COMBO": { packaging: "Pouch", noOfPkt: 40, noOfUnits: 100, mrp: 50 },
  "PURE COCONUT": { packaging: "Pouch", noOfPkt: 40, noOfUnits: 100, mrp: 50 },
  "HAPPY BIRTHDAY": {
    packaging: "Pouch",
    noOfPkt: 40,
    noOfUnits: 100,
    mrp: 50,
  },
  "KESAR PENDA": { packaging: "Pouch", noOfPkt: 40, noOfUnits: 100, mrp: 50 },
};

export const productObj: productType = {
  "chocolate bar": [
    {
      name: "Dairy Kiss Blue ₹10 ",
      url: "/images/chocolatebar/Cocoa Milk Choclate Bar.webp",
      price: 1,
      desc: descriptionObj["DAIRY KISS1"],
    },
    {
      name: "Dairy Kiss Blue ₹5",
      url: "/images/chocolatebar/Dairy Kiss Cocoa.webp",
      price: 5,
      brand: "dairy kiss",
      desc: descriptionObj["BIG ROLLE CHOC"],
    },
    {
      name: "Dairy Kiss Container",
      url: "/images/centerMissing/Dairy Kiss Container.webp",
      price: 5,
      brand: "dairy kiss",
      desc: descriptionObj["DAIRY KISS BLUE CONT (30 PCS)"],
    },
    {
      name: "Dairy Kiss Strawberry",
      url: "/images/chocolatebar/StrawBerry Bar.webp",
      price: 5,
      desc: descriptionObj["BIG ROLLE CHOC"],
    },
    {
      name: "Dairy Kiss Black & White ",
      url: "/images/chocolatebar/Black & White Bar.webp",
      price: 5,
      category: "c-1",
      desc: descriptionObj["BIG ROLLE CHOC"],
    },
    {
      name: "Dairy Kiss Milk ",
      url: "/images/chocolatebar/Milkies Milk Choclate Bar.webp",
      price: 5,
      desc: descriptionObj["DAIRY KISS BLUE"],
    },
    {
      name: "Dairy Kiss Coconut ",
      url: "/images/chocolatebar/Coconut Bar.webp",
      price: 5,
      desc: descriptionObj["DAIRY KISS BLUE"],
    },

    {
      name: "Dairy Kiss Dark",
      url: "/images/chocolatebar/Dark Milk Choclate Bar.webp",
      price: 5,
      desc: descriptionObj["DAIRY KISS BLUE"],
    },
    {
      name: "Dairy Kiss Gold",
      url: "/images/chocolatebar/Milk Choclate Bar.webp",
      price: 5,
      desc: descriptionObj["DAIRY KISS BLUE"],
    },
    {
      name: "Dairy Kiss Red",
      url: "/images/chocolatebar/HazelNut Bar.webp",
      price: 5,
      desc: descriptionObj["DAIRY KISS BLUE"],
    },
    {
      name: "Dairy Kiss Blue ₹2",
      url: "/images/centerMissing/Dairy Kiss Milk Cocoa.webp",
      price: 2,
      brand: "dairy kiss",
      desc: descriptionObj["DAIRY KISS"],
    },
    {
      name: "Dairy Kiss Milkies",
      url: "/images/centerMissing/Dairy Kiss Milk Box.webp",
      price: 5,
      brand: "dairy kiss",
      desc: descriptionObj["DAIRY KISS BLUE"],
    },
    {
      name: "Safari Park",
      url: "/images/chocolatebar/Safari Park.webp",
      price: 2,
      desc: descriptionObj["SAFARI PARK"],
    },
  ],
  "centerfilled chocolate": [
    {
      name: "Truffle Milk 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE MILK 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Truffle Blueberry 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE BLUBERRY 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Truffle Milk Gift Box",
      url: "/images/centerfilledchocolate/TRUFFLES MILK GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
      desc: descriptionObj["TRUFFLE SMALL"],
      isGifting: true,
    },
    {
      name: "Truffle Blueberry Gift Box",
      url: "/images/centerfilledchocolate/TRUFFLE BLUE BERRY GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Milk Big",
      url: "/images/centerfilledchocolate/TRUFFLE MILK 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
      desc: descriptionObj["BIG TRUFFLE"],
    },
    {
      name: "Truffle Blueberry Big",
      url: "/images/centerfilledchocolate/TRUFFLE BUEBERRY 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffle Pouch",
      url: "/images/centerfilledchocolate/TRUFFLES BLUE POUCH 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles Pouch",
      brand: "truffle",
      desc: descriptionObj["TRUFFLE POUCH"],
    },
    {
      name: "Truffle Octagon Container",
      url: "/images/centerfilledchocolate/TRUFFLE CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      // subCategory: "Truffles 30 Pcs Container",
      brand: "truffle",
      desc: descriptionObj["TRuffle OCtagon heart"], //gram instead of units
      isGifting: true,
    },
    {
      name: "Truffle Heart Container",
      url: "/images/centerfilledchocolate/TRUFFLE GIFT CONTAIER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 30 Pcs Container",
      brand: "truffle",
      desc: descriptionObj["TRuffle OCtagon"], //gram instead of units
      isGifting: true,
    },
    // {
    //   name: "Truffle Milk 70 Pcs",
    //   url: "/images/centerfilledchocolate/TRUFFLE MILK 70 PCS 5RS.webp",
    //   price: 5,
    //   brand: "truffle",
    // },
    {
      name: "Truffle Pistachio 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE PISTACHIO 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Pistachio Big",
      url: "/images/centerfilledchocolate/TRUFFLE PISTACHIO 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffle Rajbhog 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE RAJBHOG 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Rajbhog Big",
      url: "/images/centerfilledchocolate/TRUFFLE RAJBHOG 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffle Rajbhog Gift Box",
      url: "/images/centerfilledchocolate/TRUFFLE RAJBHOG GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Strawberry 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE STRAWBERRY 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Strawberry Big",
      url: "/images/centerfilledchocolate/TRUFFLE STRAWBERRY 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffle 70 Pcs Container",
      url: "/images/centerfilledchocolate/TRUFFLES CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 Pcs Container",
      brand: "truffle",
      desc: descriptionObj["Truffle Container 70"],
    },
    {
      name: "Truffle 70 Pcs Container",
      url: "/images/centerfilledchocolate/TRUFFLES CONTAINER 2 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 Pcs Container",
      brand: "truffle",
      desc: descriptionObj["Truffle Container 70"],
    },
    {
      name: "Truffle Pouch",
      url: "/images/centerfilledchocolate/TRUFFLES RED POUCH 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles Pouch",
      brand: "truffle",
    },
    {
      name: "Truffle Container",
      url: "/images/centerfilledchocolate/TRUFFLE.png",
      price: 5,
      category: "Single Twist",
      desc: descriptionObj["TRUFFLE CONTAINER (30 PCS)"],
    },
    {
      name: "Truffle Strawberry Gift Box",
      url: "/images/centerfilledchocolate/TRUFFLES STRAWBERRY GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Pistachio Gift Box",
      url: "/images/centerfilledchocolate/TRUFFLES PISTACHIO GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },

    {
      name: "D'Love Gold 70 Pcs",
      url: "/images/centerfilledchocolate/DLOVE GOLD 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 70Pcs Box",
      brand: "d love",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "D'Love Gold Pouch",
      url: "/images/centerfilledchocolate/DLOVE GOLD POUCH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold Pouch",
      brand: "d love",
      desc: descriptionObj["D'LOVE GOLD POUCH"],
    },
    {
      name: "D'Love Gold Container",
      url: "/images/centerMissing/D'LOVE GOLD CONTAINER.png",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 30Pcs Container",
      brand: "d love",
      desc: descriptionObj["D'LOVE MIX CONT (30 PCS)"],
      isGifting: true,
    },
    {
      name: "D'Love Assorted Container",
      url: "/images/centerMissing/ASSOTED CONTAINER.png",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 40Pcs Container",
      brand: "d love",
      desc: descriptionObj["D'LOVE MIX CONT (30 PCS)"],
      isGifting: true,
    },
    {
      name: "D'Love Gold Big",
      url: "/images/centerMissing/D'Love Gold.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 2Kg Box",
      brand: "d love",
      desc: descriptionObj["BIG TRUFFLE"],
    },
    {
      name: "D'Love Assorted 70 Pcs",
      url: "/images/centerfilledchocolate/DLOVE PURPULE 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel 70Pcs Box",
      brand: "d love",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "D'Love Green 70 Pcs",
      url: "/images/centerfilledchocolate/DLOVE GREEN5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel 70Pcs Box",
      brand: "d love",
    },
    {
      name: "D'Love Pink 70 Pcs",
      url: "/images/centerMissing/D'Love Pink.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel 70Pcs Box",
      brand: "d love",
    },
    {
      name: "D'Love Assorted Pouch",
      url: "/images/centerfilledchocolate/DLOVE GREEN POUH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel Pouch",
      brand: "d love",
      desc: descriptionObj["D'LOVE GOLD POUCH"],
    },
    {
      name: "D'Love Pink Pouch",
      url: "/images/centerfilledchocolate/DLOVE PINK POUCH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel Pouch",
      brand: "d love",
      desc: descriptionObj["D'LOVE GOLD POUCH"],
    },
    {
      name: "D'Love Red 70 Pcs",
      url: "/images/centerfilledchocolate/DLOVE RED 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Red 70Pcs Box",
      brand: "d love",

      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "D'Love Red Jar",
      url: "/images/centerMissing/DLOVE RED JAR.png",
      price: 5,
      category: "Bunch Wrap",
      subCategory: "Dlove Red Jar",
      brand: "d love",
      desc: descriptionObj["D'LOVE GOLD JAR"],
      isGifting: true,
    },
    {
      name: "D'Love Gold Jar",
      url: "/images/centerMissing/DLOVE GOLD JAR.png",
      price: 5,
      category: "Bunch Wrap",
      desc: descriptionObj["D'LOVE GOLD JAR"],
      brand: "d love",
      isGifting: true,
    },
    {
      name: "D'Love Assorted Jar",
      url: "/images/centerMissing/DLOVE ASSORTED JAR.png",
      price: 5,
      category: "Bunch Wrap",
      desc: descriptionObj["D'LOVE GOLD JAR"],
      brand: "d love",
      isGifting: true,
    },
    // {
    //   name: "Amore 70 Pcs",
    //   url: "/images/DAZZY LOGO.webp",
    //   price: 5,
    //   category: "Pillow Pack",
    //   subCategory: "Amore 70Pcs Box",
    //   desc: descriptionObj["TRUFFLE"],
    // },
    // {
    //   name: "Amore Container",
    //   url: "/images/DAZZY LOGO.webp",
    //   price: 5,
    //   category: "Pillow Pack",
    //   subCategory: "Amore 30Pcs Container",
    //   desc: descriptionObj["TRUFFLE CONTAINER"],
    // },
    {
      name: "Delite Pistachio 70 Pcs",
      url: "/images/centerfilledchocolate/DELIGHT PISTACGIO 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Delite Container",
      url: "/images/centerMissing/DELITE CONTAINER.png",
      price: 5,
      category: "Pillow Pack",
      desc: descriptionObj["DELITE CONT (30 PCS)"],
    },
    {
      name: "Delite Rajbhog 70 Pcs ",
      url: "/images/centerfilledchocolate/DELIGHT RAJBHOG 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },

    {
      name: "Delite Strawberry 70 Pcs ",
      url: "/images/centerfilledchocolate/DELIGHT STRAWBERRY 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Delite Cashewnut 70 Pcs ",
      url: "/images/centerfilledchocolate/DELIGHT CAHEWNUT 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Delite Mango 70 Pcs ",
      url: "/images/centerfilledchocolate/DELIGHT MANGO 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },

    {
      name: "Delite Pistachio Big",
      url: "/images/centerfilledchocolate/DELIGHT PISTACHIO 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "Delite Rajbhog Big",
      url: "/images/centerfilledchocolate/DELIGHT RAJBHOG 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Delite Strawberry Big",
      url: "/images/centerfilledchocolate/DELIGHT STRAWBERRY150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Delite Mango Big",
      url: "/images/centerfilledchocolate/DELIGHT MANGO150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },

    {
      name: "Delite Blueberry Big",
      url: "/images/centerfilledchocolate/DELIGHT BLUEBERRY 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Cocos 70 Pcs",
      url: "/images/centerfilledchocolate/COCOS  TRUFFLES BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Cocos 70pcs Box",
      brand: "cocos",
      desc: descriptionObj["TRUFFLE"],
    },

    {
      name: "Cocos Pouch",
      url: "/images/centerfilledchocolate/COCOS  TRUFFLES POUCH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Cocos Pouch",
      brand: "cocos", 
      desc: descriptionObj["COcos Pouch"]
    },
    {
      name: "Bliss Dark 125 Pcs",
      url: "/images/centerfilledchocolate/BLISS DARK 1RS.webp",
      price: 1,
      category: "Pillow Pack",
      subCategory: "Bliss 125pcs Box",
      desc: descriptionObj["BLISS CHOCO"],
    },

    {
      name: "Bliss Strawberry 125 Pcs",
      url: "/images/centerfilledchocolate/BLISS STRAWBERRY 1RS.webp",
      price: 1,
      category: "Pillow Pack",
      subCategory: "Bliss 125pcs Box",
      desc: descriptionObj["BLISS CHOCO"],
    },

    {
      name: "Bliss Milk 125 Pcs ",
      url: "/images/centerfilledchocolate/BLISS WHITE 1RS.webp",
      price: 1,
      category: "Pillow Pack",
      subCategory: "Bliss 125pcs Box",
      desc: descriptionObj["BLISS CHOCO"],
    },
    {
      name: "DeGold 125 Pcs",
      url: "/images/centerfilledchocolate/GOLD BOX2RS 2.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Gold 125Pcs Box",
      brand: "gold",
      desc: descriptionObj["ENDON"],
    },
    {
      name: "DeGold 125 Pcs",
      url: "/images/centerfilledchocolate/GOLD BOX2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Gold 125Pcs Box",
      brand: "gold",
      desc: descriptionObj["ENDON"],
    },
    {
      name: "DeGold Container",
      url: "/images/centerMissing/D GOLD CONTAINER.png",
      price: 2,
      category: "Pillow Pack",
      brand: "endon", 
      isGifting: true,
      desc: descriptionObj["Endon Containerss"]
      
    },
    {
      name: "Emporio 70 Pcs",
      url: "/images/centerfilledchocolate/EMPORIO 70PCS BOX 5RS.webp",
      price: 5,
      brand: "Emporio",
      category: "Pillow Pack",
      desc: descriptionObj["TRUFFLE"],
      subCategory: "Empirio Box ",
    },
    {
      name: "Emporio Pouch",
      url: "/images/centerfilledchocolate/EMPORIO POUCH  5RS.webp",
      price: 5,
      brand: "Emporio",
      category: "Pillow Pack",
      desc: descriptionObj["TRUFFLE POUCH"],
    },

    {
      name: "Emporio Container",
      url: "/images/centerMissing/EMPORIO CONTAINER.png",
      price: 5,
      brand: "Emporio",
      category: "Pillow Pack",
      // subCategory: "Empirio Box ",
      desc: descriptionObj["DELITE CONT (30 PCS)"],
      isGifting: true,
    },
    {
      name: "Empirio 70 Pcs",
      url: "/images/centerfilledchocolate/EMPIRIO BOX 5RS.webp",
      price: 5,
      brand: "Emporio",
      category: "Pillow Pack",
      subCategory: "Empirio Box ",
    },
    {
      name: "DeGold 60 Pcs",
      url: "/images/centerfilledchocolate/GOLD GIFTBOX2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "DGold 60Pcs Box",
      desc: descriptionObj["ENDON SMALL BOX"],
    },

    {
      name: "DGold 60Pcs Box",
      url: "/images/centerfilledchocolate/GOLD GIFT BOX2RS 2.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "DGold 60Pcs Box",
      desc: descriptionObj["ENDON SMALL BOX"],
    },
    {
      name: "Endon 60 Pcs",
      url: "/images/centerfilledchocolate/ENDON GIFT BOX 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 60Pcs Box",
      brand: "endon",
      desc: descriptionObj["ENDON SMALL BOX"],
      isGifting: true,
    },

    {
      name: "Endon 60 Pcs",
      url: "/images/centerfilledchocolate/ENDON GOFT BOX1 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 60Pcs Box",
      brand: "endon",
      desc: descriptionObj["ENDON SMALL BOX"],
    },
    {
      name: "Endon 125 Pcs",
      url: "/images/centerfilledchocolate/ENDON BOX 125 PCS 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 125Pcs Box",
      brand: "endon",
      desc: descriptionObj["ENDON"],
    },
    {
      name: "Endon 125 Pcs",
      url: "/images/centerfilledchocolate/ENDON BOX 125 PCS2 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 125Pcs Box",
      brand: "endon",
    },
    {
      name: "Endon Container",
      url: "/images/centerMissing/ENDON CONTAINER.png",
      price: 2,
      category: "Pillow Pack",

      brand: "endon", 
      isGifting: true,
      desc: descriptionObj["Endon Containerss"]

    },
    {
      name: "Glorious Pistachio 70 Pcs",
      url: "/images/centerfilledchocolate/GLORIOUS PISTACHIO5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Glorious Chocolate 70 Pcs",
      url: "/images/centerfilledchocolate/GLORIOUS CHOCOLATE 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Glorious Gift Box",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious Gift Box",
      desc: descriptionObj["BOlivia gift box"],
      isGifting: true,
    },
    {
      name: "Glorious Cashewnut Big",
      url: "/images/centerMissing/Glorious Cashewnut.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "Glorious chocolate Big",
      url: "/images/centerMissing/Glorious Chocolait.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "Glorious Milk Big",
      url: "/images/centerMissing/Glorious Milk.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "Glorious Pistachio Big",
      url: "/images/centerMissing/Glorious Pistachio.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "Glorious Rajbhog Big",
      url: "/images/centerMissing/Glorious Rajbhog.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
      desc: descriptionObj["BIG DELITE"],
    },
    // {
    //   name: "Glorious Cashewnut",
    //   url: "/images/centerfilledchocolate/GLORIOUS CCASHEWNUT 5RS.webp",
    //   price: 5,
    //   category: "Single Twist",
    //   subCategory: "Glorious 70 pcs",
    // },
    {
      name: "Glorious Heart Container",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 30Pcs Container",
      desc: descriptionObj["TRuffle OCtagon"], //gram instead of units
      isGifting: true,
    },
    {
      name: "Glorious Heart Container",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT CONTAINER (2) 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 30Pcs Container",
    },
    {
      name: "Glorious Heart Container",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT CONTAINER (3) 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 30Pcs Container",
    },
    {
      name: "Glorious Milk 70 Pcs",
      url: "/images/centerfilledchocolate/GLORIOUS MILK 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
    },
    {
      name: "Glorious Rajbhog 70 Pcs",
      url: "/images/centerfilledchocolate/GLORIOUS RAAJBHOG 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
    },
    {
      name: "Glorious Cashewnut 70 Pcs",
      url: "/images/centerfilledchocolate/KAJUNUT.png",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
    },
        {
      name: "Glorious Container ",
      url: "/images/centerfilledchocolate/GLORIOUS.png",
      price: 5,
      category: "Single Twist",
      desc: descriptionObj["TRUFFLE CONTAINER (30 PCS)"]

    },

    {
      name: "Gold 50 Pcs",
      url: "/images/centerfilledchocolate/GOLD GIFT BOX 2RS.webp",
      price: 2,
      category: "Bunch Wrap",
      subCategory: "Gold Box",
      brand: "gold",
      desc: descriptionObj["GOLD BOX"],
    },
    {
      name: "Gold Jar",
      url: "/images/centerfilledchocolate/GOLD ROUND JAR 2RS.webp",
      price: 2,
      category: "Bunch Wrap",
      subCategory: "Gold Jar",
      brand: "gold",
      desc: descriptionObj["GOLD JAR"],
    },
    {
      name: "United 50 Pcs",
      url: "/images/centerfilledchocolate/UNITED GIFT BOX 2RS.webp",
      price: 2,
      category: "Bunch Wrap",
      subCategory: "United Box",
      desc: descriptionObj["GOLD BOX"],
    },
    {
      name: "United Jar",
      url: "/images/centerfilledchocolate/UNITED JAR 2RS.webp",
      price: 2,
      category: "Bunch Wrap",
      subCategory: "United Jar",
      desc: descriptionObj["UNITED JAR"],
    },

    {
      name: "D'Love Gold Big",
      url: "/images/centerfilledchocolate/D LOVE GOLD 150 PCS 5RS.webp",
      price: 5,
      brand: "d love",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "D'Love Pestal Big",
      url: "/images/HAPPY DHANTERAS DAZZY (1).png",
      price: 5,
      brand: "d love",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "Delite Cashewnut Big",
      url: "/images/centerfilledchocolate/DELIGHT CASHEWNUUT 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "MerOne 125 Pcs",
      url: "/images/centerfilledchocolate/MERONE 125PCS  2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Merone 125pcs Box",
      desc: descriptionObj["ENDON"],
    },
    {
      name: "Stacy Octagon Container",
      url: "/images/centerfilledchocolate/STACY GIFT CONTAINER  5RS.webp",
      price: 5,
      desc: descriptionObj["TRuffle OCtagon heart"], //gram instead of units
    },
    {
      name: "Delite Blueberry 70 Pcs",
      url: "/images/centerfilledchocolate/DELIGHT BLUEBERRY 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
    },

    {
      name: "Stacy 70 Pcs",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 70pcs",
      desc: descriptionObj["STACY BOX"],
    },
    {
      name: "Stacy Box 70 Pcs ",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS 2  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 70pcs",
      desc: descriptionObj["STACY BOX"],
    },
    {
      name: "Stacy Box 70 Pcs ",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS 1.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 70pcs",
      desc: descriptionObj["STACY BOX"],
    },
    {
      name: "Stacy Gift Box ",
      url: "/images/centerfilledchocolate/STACY GIFT BOX 1  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 20pcs",
      desc: descriptionObj["STACY SMALL"],
      isGifting: true,
    },
    {
      name: "Stacy Gift Box ",
      url: "/images/centerfilledchocolate/STACY GIFT BOX 2  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 20pcs",
      desc: descriptionObj["STACY SMALL"],
    },
    {
      name: "Stacy Gift Box",
      url: "/images/centerfilledchocolate/STACY GIFT BOX  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 20pcs",
      desc: descriptionObj["STACY SMALL"],
    },
    // {
    //   name: "Stacy Octagon",
    //   url: "/images/centerMissing/STACY OCTAGON.png",
    //   price: 5,
    //   category: "Double Twist",
    //   desc: descriptionObj["TRUFFLE OCTAGON"],
    //   isGifting: true,
    // },
    {
      name: "Stacy Container",
      url: "/images/centerfilledchocolate/STACY CONTAINER  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Container",
      desc: descriptionObj["STACY CONT"],
    },
    // {
    //   name: "Stacy Gift Box",
    //   url: "/images/centerfilledchocolate/STACY GIFT BOX  5RS.webp",
    //   price: 5,
    // },

    {
      name: "Bolivia 70 Pcs",
      url: "/images/centerfilledchocolate/BOLIVIA 70 PCS BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 70 Pcs Box",
      brand: "bolivia",
      desc: descriptionObj["TRUFFLE"],
    },

        {
      name: "Bolivia Big Box",
      url: "/images/centerfilledchocolate/BOLIVIA150 PCS BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 150 Pcs Box",
      brand: "bolivia",
      desc: descriptionObj["BIG DELITE"],
    },
    {
      name: "Bolivia Gift Box",
      url: "/images/centerfilledchocolate/BOLIVIA GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 25Pcs Box",
      brand: "bolivia",
      desc: descriptionObj["BOlivia gift box"],
      isGifting: true,
    },

    {
      name: "Chocobon Container",
      url: "/images/centerMissing/CHOCO BON CONTAINER 1.png",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Container",
      brand: "choco bon",
      desc: descriptionObj["TRUFFLE CONTAINER (30 PCS)"],
      isGifting: true,
    },
    {
      name: "Chocobon Container",
      url: "/images/centerMissing/CHOCO BON CONTAINER 2.png",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Container",
      brand: "choco bon",
      desc: descriptionObj["TRUFFLE CONTAINER (30 PCS)"],
    },
    {
      name: "Chocobon Pistachio 70 Pcs",
      url: "/images/centerfilledchocolate/CHOCOBON PISTACHIO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
      desc: descriptionObj["TRUFFLE"],
    },

    {
      name: "Chocobon Coconut 70 Pcs",
      url: "/images/centerfilledchocolate/CHOCOBON COCONUT  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
    },
    {
      name: "Chocobon Strawberry 70 Pcs",
      url: "/images/centerfilledchocolate/CHOCOBON STRAWBERRY  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
    },
    {
      name: "Chocobon Mango 70 Pcs",
      url: "/images/centerfilledchocolate/CHOCOBON MANGO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
    },
    {
      name: "Ferola Milk 70 Pcs",
      url: "/images/centerfilledchocolate/FEROLA MILK  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Ferola Coconut 70 Pcs",
      url: "/images/centerfilledchocolate/FEROLA COCONUT  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Ferola Mango 70 Pcs",
      url: "/images/centerfilledchocolate/FEROLA MANGO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Ferola Pistachio 70 Pcs",
      url: "/images/centerfilledchocolate/FEROLA PISTACHIO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Ferola Strawberry 70 Pcs",
      url: "/images/centerfilledchocolate/FEROLA STRAWBERRY  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
    },
    {
      name: "Ferola Container",
      url: "/images/centerMissing/FEROLA CONTAINER 1.png",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Container",
      desc: descriptionObj["TRUFFLE CONTAINER (30 PCS)"],

      isGifting: true,
    },
    {
      name: "Ferola Container",
      url: "/images/centerMissing/FEROLA CONTAINER 2.png",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Container",
      desc: descriptionObj["TRUFFLE CONTAINER"],
    },

    {
      name: "Stacy Mini's Matka Jar",
      url: "/images/centerfilledchocolate/STACY MINIS JAR 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Mini MatkaJar",
      desc: descriptionObj["STACY MINI'S MATKA JAR"],
    },
    {
      name: "Stacy Mini's Container",
      url: "/images/centerfilledchocolate/STACY MINIS CONTAINER 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Mini Container",
      desc: descriptionObj["STACY MINI'S CONTAINER"],
    },
    {
      name: "Stacy Mini's Gift Box",
      url: "/images/centerfilledchocolate/STACY MINIS GIFT BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Minis 50Pcs Box",
      desc: descriptionObj["STACY MINI'S SMALL BOX"],
      isGifting: true,
    },
    {
      name: "Stacy Mini's 125 Pcs",
      url: "/images/centerfilledchocolate/STACY MINIS 125 PCS BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Minis 125 Pcs Box",
      desc: descriptionObj["STACY MINI'S BOX"],
      
    },
        {
      name: "Stacy Mini's Container",
      url: "/images/centerfilledchocolate/STACY CHOCOLATE CANTAINER  5RS.webp",
      price: 2,
      category: "Double Twist",
      desc: descriptionObj["Stacy MIni COnt"],
      brand:"Stacy",
    },
    {
      name: "Brevo 50 Pcs",
      url: "/images/centerfilledchocolate/BREVO GIFT BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Brevo 50Pcs Box",
      desc: descriptionObj["BREVO SMALL BOX"],
      isGifting: true,
    },

    {
      name: "Brevo 125 Pcs",
      url: "/images/centerfilledchocolate/BREVO 125 PCS BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Brevo 125Pcs Box",
      desc: descriptionObj["BREVO"],
    },
    {
      name: "Brevo Container",
      url: "/images/centerfilledchocolate/BREVO CONTAINER 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Brevo Container",
      desc: descriptionObj["BREVO CONTAINER"],
    },

    {
      name: "Bolivia Container 70 Pcs",
      url: "/images/centerfilledchocolate/BOLIVIA CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 70Pcs Container",
      brand: "bolivia",
      desc: descriptionObj["STACY CONT"],
    },
    {
      name: "Bolivia Container 30 Pcs",
      url: "/images/centerfilledchocolate/BOLIVIA CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      brand: "bolivia",
      desc: descriptionObj["TRUFFLE CONTAINER (30 PCS)"]

    },
    {
      name: "Bolivia Jewel Container",
      url: "/images/centerMissing/Bolivia Container.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia Container",
      brand: "bolivia",
      desc: descriptionObj["BOlivia MIni COnt"],
      isGifting: true,
    },
    {
      name: "Chocobon Milk 70 Pcs",
      url: "/images/centerfilledchocolate/CHOCOBON MILK  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Truffins 30 Pcs",
      url: "/images/centerfilledchocolate/TRUFFINS 30 PCS 5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffles 30 Pcs", 
      desc: descriptionObj["Truffins Box 3opcs"],
    },
    {
      name: "Truffins 30 Pcs",
      url: "/images/centerfilledchocolate/TRUFFINS 30 PCS 1  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffles 30 Pcs",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Truffins 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFINS 70 PCS  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffins 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Truffins 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFINS 70 PCS 1  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffins 70Pcs Box",
    },
    {
      name: "Truffins Container",
      url: "/images/centerfilledchocolate/TRUFFINS CONTAINER  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffins Container", 
      desc: descriptionObj["Truffins Cont"],
    },

    {
      name: "Orientto Coconut 70 Pcs",
      url: "/images/centerMissing/Orientto Coconut.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Orientto Hazelnut 70 Pcs ",
      url: "/images/centerMissing/Orientto Hazalnut.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Orientto Milk 70 Pcs",
      url: "/images/centerfilledchocolate/Orientto Milk.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Orientto Mango 70 Pcs",
      url: "/images/centerMissing/Orientto Pista .webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    {
      name: "Orientto Strawberry 70 Pcs",
      url: "/images/centerMissing/Orientto Strwberry.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
      desc: descriptionObj["TRUFFLE"],
    },
    // {
    //   name: "Oriento 2Kg Box",
    //   url: "/images/centerfilledchocolate/GLORIOUS GIFT BOX 253RS.webp",
    //   price: 5,
    //   category: "Single Twist",
    //   subCategory: "Oriento 2Kg Box",
    // },
    // {
    //   name: "Oriento Container 30 Pcs ",
    //   url: "/images/DAZZY LOGO.webp",
    //   price: 5,
    //   category: "Single Twist",
    //   subCategory: "Oriento 30pcs Container", ///matter lest
    // },
    {
      name: "Maxic Box 125 Pcs",
      url: "/images/centerfilledchocolate/MAXIC  BOX 125 PCS 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Maxic Box 125 Pcs",
      desc: descriptionObj["ENDON"],
    },
    {
      name: "Maxic 50 Pcs",
      url: "/images/centerfilledchocolate/MAXIC GIFT BOX 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Maxic 50Pcs Box",
      desc: descriptionObj["ENDON SMALL BOX"],
    },
    {
      name: "Belgium 125 Pcs ",
      url: "/images/centerfilledchocolate/BELGIUM 125 PCS 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Belgium 125 Pcs Box",
      desc: descriptionObj["ENDON"],
    },
    {
      name: "Belgium 50 Pcs",
      url: "/images/centerfilledchocolate/BELGIAM GIFT BOX 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Belgiam 50Pcs Box",
      desc: descriptionObj["ENDON SMALL BOX"],
    },
  ],
  "decorative chocolate": [
    {
      name: "King Kong",
      url: "/images/decorativechocolate/KING KONG 1 5RS.webp",
      price: 5,
      desc: descriptionObj["KING KONG"],
      subCategory: "Belgiam 50Pcs Box",
    },

    {
      name: "King Kong",
      url: "/images/decorativechocolate/KING KONG 5RS.webp",
      price: 5,
      desc: descriptionObj["KING KONG"],
      subCategory: "Belgiam 50Pcs Box",
    },
    {
      name: "Dr.Teddy",
      url: "/images/decorativechocolate/DR TEDDY5RS.webp",
      price: 5,
      brand: "dr. teddy",
      desc: descriptionObj["KING KONG"],
      subCategory: "Belgiam Box",
    },
    {
      name: "Dr.Teddy",
      url: "/images/decorativechocolate/DR TEDDY25RS.webp",
      price: 25,
      brand: "dr. teddy",
      desc: descriptionObj["KING KONG"],
      subCategory: "Belgiam Box",
    },

    {
      name: "Choco Toco ₹10 ",
      url: "/images/decorativechocolate/CHOCO TOCON 10RS.webp",
      price: 10, 
      desc: descriptionObj["CHOCO TOCO"],
    },
    {
      name: "Choc Cone ₹5",
      url: "/images/decorativechocolate/CHOCO COAN 5RS.webp",
      price: 5,
      desc: descriptionObj["CHOC CONE"],

    },
  ],
  "Crunchy chocolate": [
    {
      name: "Oh! Wow 125 Pcs",
      url: "/images/peanut chocolate/OH WOW BIG BOX.webp",
      price: 5,
      brand: "oh! wow",
      desc: descriptionObj["OH! WOW BOX"],
    },
    {
      name: "Oh! Wow Pouch",
      url: "/images/peanut chocolate/OH WOW POUCH.webp",
      price: 2,
      brand: "oh! wow",
      desc: descriptionObj["OH WOW CENTERSEAL POUCH"],
    },
    {
      name: "Oh! Wow Gift Box",
      url: "/images/peanut chocolate/OH WOW SMALL BOX.webp",
      price: 2,
      brand: "oh! wow",
      desc: descriptionObj["OH WOW GIFT BOX"],
    },
    {
      name: "Oh! Wow Standy Pouch",
      url: "/images/peanut chocolate/OH WOW STANDY POUCH.webp",
      price: 2,
      brand: "oh! wow",
      desc: descriptionObj["OH WOW STANDEE POUCH"],
    },
    {
      name: "Oh! Wow Container",
      url: "/images/centerMissing/OH!WOW CONTAINER.png",
      price: 2,
      brand: "oh! wow",
      desc: descriptionObj["OH! WOW CONT"],
    },
    {
      name: "Caranut ",
      url: "/images/peanut chocolate/CARANUT BOX.webp",
      price: 5,
      desc: descriptionObj["CARANUT"],
    },
    {
      name: "Chokers ",
      url: "/images/peanut chocolate/CHOKERS BOX.webp",
      price: 5,
      desc: descriptionObj["CARANUT"],
    },
    {
      name: "Chokers Container",
      url: "/images/peanut chocolate/CHOKERS CONTAINER.webp",
      price: 5,
      desc: descriptionObj["CHOKERS CONT (30 PCS)"],
    },
  ],
  "nought bar": [
    {
      name: "Big Star Container",
      url: "/images/nugut bar/BIG STAR.webp",
      price: 5,
      brand: "big star",
      desc: descriptionObj["BIG STAR CONT (30 PCS)"],
    },
    {
      name: "Big Star",
      url: "/images/nugut bar/BIG STAR BOX.webp",
      price: 5,
      brand: "big star",
      desc: descriptionObj["BIG STAR"],
    },
    {
      name: "Chockers Container",
      url: "/images/nugut bar/CHOKERS CONTAINER 5RS.webp",
      price: 5,
      desc: descriptionObj["BIG STAR CONT (30 PCS)"],
    },
    {
      name: "Chockers",
      url: "/images/nugut bar/CHOKERS BOX5RS.webp",
      price: 5,
      desc: descriptionObj["BIG STAR"],
    },
    {
      name: "Tornutte Container",
      url: "/images/nugut bar/TORNUTTE  BAR CONTAINER.webp",
      price: 5,
      desc: descriptionObj["BIG STAR CONT (30 PCS)"],
    },
    {
      name: "Tornutte",
      url: "/images/nugut bar/TORNUTTE  BAR BOX.webp",
      price: 5,
      desc: descriptionObj["BIG STAR"],
    },

    {
      name: "Caranut Container",
      url: "/images/centerMissing/CARANUT CONTAINER.png",
      price: 5,
      desc: descriptionObj["BIG STAR CONT (30 PCS)"],
    },
    {
      name: "Carafins Container ",
      url: "/images/centerMissing/CARAFINS.png",
      price: 5,
      desc: descriptionObj["BIG STAR CONT (30 PCS)"],
    },
    {
      name: "Brackers",
      url: "/images/nugut bar/BRACKERS BOX.webp",
      price: 5,
      desc: descriptionObj["BIG STAR"],
    },
  ],

  "wafer rolls": [
    {
      name: "3 Stix Choco fills",
      url: "/images/wafffer rolls/3 stix chocofills.webp",
      price: 5,
      brand: "3 stix",
      desc: descriptionObj["3 STIX CHOCO"],
    },
    {
      name: "3 Stix Milk Fills",
      url: "/images/wafffer rolls/3stix milk fills.webp",
      price: 5,
      brand: "3 stix",
      desc: descriptionObj["3 STIX CHOCO"],
    },
    {
      name: "3 Stix Kraks",
      url: "/images/wafffer rolls/3 stix kraks.webp",
      price: 5,
      brand: "3 stix",
      desc: descriptionObj["3 STIX CHOCO"],
    },

    {
      name: "Big Rolle Chocolate",
      url: "/images/wafffer rolls/big roll chocolate.webp",
      price: 5,
      brand: "big rolle",
      desc: descriptionObj["BIG ROLLE CHOC"],
    },
    {
      name: "Big Rolle Dark",
      url: "/images/wafffer rolls/big roll dark.webp",
      price: 5,
      brand: "big rolle",
      desc: descriptionObj["BIG ROLLE CHOC"],
    },
    {
      name: "Big Rolle Milk",
      url: "/images/wafffer rolls/big roll milk.webp",
      price: 5,
      brand: "big rolle",
      desc: descriptionObj["BIG ROLLE CHOC"],
    },
    {
      name: "Choc Stix Jar",
      url: "/images/wafffer rolls/choco stix.webp",
      price: 5,
      brand: "3 stix",
      desc: descriptionObj["ROLLE STIX"],
    },

    {
      name: "Rolle Stix Jar",
      url: "/images/wafffer rolls/rolle stix.webp",
      price: 5,
      brand: "3 stix",
      desc: descriptionObj["ROLLE STIX"],
    },
    {
      name: "Dark Stix Jar",
      url: "/images/wafffer rolls/dark stix.webp",
      price: 5,
      brand: "3 stix",
      desc: descriptionObj["ROLLE STIX"],
    },
    {
      name: "Krack Stix Jar",
      url: "/images/wafffer rolls/krack stix.webp",
      price: 5,
      brand: "3 stix",
      desc: descriptionObj["ROLLE STIX"],
    },

    {
      name: "Waffo Roll",
      url: "/images/wafffer rolls/wafeer roll.webp",
      price: 5,
      desc: descriptionObj["BIG WOFFO ROLL"],
    },
  ],
  toffee: [
    {
      name: "Eclairs Coconut Cream",
      url: "/images/toffee/eclair coconut cream 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
      desc: descriptionObj["ECLAIRS DARK POUCH"],
      isGifting: true,
    },
    {
      name: "Cocotana Pouch",
      url: "/images/toffee/Cocotana Pouch.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Cocotana Pouch",
      desc: descriptionObj["COCOTANA POUCH"],
    },
    {
      name: "Dryfruit Selections Pouch",
      url: "/images/toffee/dry fruit selection gift pouch 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Dry Fruit Selection Gift Pouch",
      desc: descriptionObj["ECLAIRS DARK POUCH"],
    },
    {
      name: "Malai Kulfi jar",
      url: "/images/toffee/malai kulfi 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Malai Kulfi jar",
      desc: descriptionObj["KESAR & KAJU KULFI"],
    },
    {
      name: "Malai Kulfi Coconut Jar",
      url: "/images/toffee/MALAI KULFI COCONUT JAR RS1.webp",
      price: 1,
      category: "Jar",
      subCategory: "Malai Kulfi Coconut Jar",
      desc: descriptionObj["KESAR & KAJU KULFI"],
    },
    {
      name: "Malai Kulfi Kesar Kaju Jar",
      url: "/images/toffee/MALAI KULFI KESAR KAJU JAR RS1.webp",
      price: 1,
      category: "Jar",
      subCategory: "Malai Kulfi Kesar Kaju Jar",
      desc: descriptionObj["KESAR & KAJU KULFI"],
    },
    {
      name: "Soffiti Jar",
      url: "/images/toffee/soffiti 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Soffitti Jar ",
      desc: descriptionObj["KESAR & KAJU KULFI"],
    },
    {
      name: "Natural Jar",
      url: "/images/toffee/NATURAL JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Natural Jar",
      desc: descriptionObj["ÉCLAIR GOLD JAR"],
    },
    {
      name: "Eclairs Gold Jar",
      url: "/images/toffee/ECLAIR GOLD JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair Gold Jar",
      brand: "gold",
      desc: descriptionObj["ÉCLAIR GOLD JAR"],
    },
    {
      name: "Kaju Butter Jar",
      url: "/images/toffee/KAJU BUTTER JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Kaju Butter Jar",
      desc: descriptionObj["ÉCLAIR GOLD JAR"],
    },
    {
      name: "Pista Butter Jar",
      url: "/images/toffee/PISTA BUTTER JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Pista Butter Jar",
      desc: descriptionObj["ÉCLAIR GOLD JAR"],
    },

    {
      name: "Kaju Butter Pouch",
      url: "/images/toffee/KAJU BUTTER POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Kaju Butter Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },

    {
      name: "Natural Pouch",
      url: "/images/toffee/NATURAL POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Natural Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },

    {
      name: "Swiss Dairy Hut Box",
      url: "/images/toffee/SWISS DAIRY ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Swiss Dairy Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Almond Hut Box",
      url: "/images/toffee/ALMOND ZUPADI  BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Almond Hut Box ",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Butterscotch Hut Box",
      url: "/images/toffee/BUTTER SCOTCH ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Butterscotch Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Cocoville Hut Box",
      url: "/images/toffee/COCOILLE ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Cocolille Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },

    {
      name: "Eclairs Dark Jar",
      url: "/images/toffee/eclair dark jar 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
      desc: descriptionObj["BLUE ÉCLAIR JAR"],
    },
    {
      name: "Goa Kaju Jar",
      url: "/images/toffee/GOA KAJU 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Goa Kaju jar",
      desc: descriptionObj["GOA ALMOND"],
    },
    {
      name: "Eclairs Almond Jar",
      url: "/images/toffee/Eclairs Almond  Jar.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
      desc: descriptionObj["ÉCLAIR GOLD JAR"],
    },
    {
      name: "Eclairs Hazelnut",
      url: "/images/toffee/eclair hazelnut 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },
    {
      name: "Eclairs Milk",
      url: "/images/toffee/eclair milk 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },
    {
      name: "Eclairs Gold Pouch",
      url: "/images/toffee/ECLAIRS GOLD POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclairs Gold Pouch",
      brand: "gold",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Goa Almond Jar",
      url: "/images/toffee/GOA ALMOND 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Goa Almond Jar",
      desc: descriptionObj["GOA ALMOND"],
    },
    {
      name: "Jewels DryFruits Pouch",
      url: "/images/toffee/JEWELS POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Jewels Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Kaju Butter Hut Box",
      url: "/images/toffee/KAJU BUTTER ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Kaju Butter Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },

    {
      name: "Natural Hut Box",
      url: "/images/toffee/NATURAL ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Natural Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Pista Butter Pouch",
      url: "/images/toffee/PISTA BUTTER POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Pista Butter Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Swiss Dairy Pouch",
      url: "/images/toffee/SWISSDAIRY POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Swissdairy Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Anjeer Hut Box",
      url: "/images/toffee/ANJEER ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Anjeer Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Butterscotch Pouch",
      url: "/images/toffee/BUTTERSCOTCH POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Butterscotch Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Coconut Butter Pouch",
      url: "/images/toffee/COCONUT BUTTER POUCH R1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Coconut Butter Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },

    {
      name: "Eclairs Coconut",
      url: "/images/toffee/eclair coconut cream gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
      desc: descriptionObj["ECLAIRS DARK BOX"],
    },

    {
      name: "Eclairs Hazelnut",
      url: "/images/toffee/eclair hazelnut gif box 2RS.webp",
      price: 2,
      subCategory: "Eclair Box ",
      desc: descriptionObj["ECLAIRS DARK BOX"],
      isGifting: true,
    },
    {
      name: "Eclairs Milk Box",
      url: "/images/toffee/eclair milk gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
      desc: descriptionObj["ECLAIRS DARK BOX"],
    },
    {
      name: "Cocotana",
      url: "/images/toffee/Cocotana.webp",
      price: 2,
      category: "Box",
      subCategory: "Cocotana Box ",
      desc: descriptionObj["Cocotana Changed"],
      isGifting: true,
    },
    {
      name: "Eclairs Milk Jar",
      url: "/images/toffee/eclairs milk jar 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Jewels DryFruits Hut Box",
      url: "/images/toffee/JEWELS ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Jewels Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Kasata Creme Hut Box",
      url: "/images/toffee/KASATA CREME  ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Kasata Creme Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Pan Bites Hut Box",
      url: "/images/toffee/PAN BITES ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Pan Bites Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Pista Harvest Container",
      url: "/images/toffee/pista harvest 2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Pista Harvest Container",
      desc: descriptionObj["HONEY CARAMEL"],
      isGifting: true,
    },
    {
      name: "Treasure Container",
      url: "/images/toffee/Trasure 2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Trasure Container",
      desc: descriptionObj["HONEY CARAMEL"],
    },
    {
      name: "Butter Feast Pouch",
      url: "/images/toffee/BUTTER FEAST POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Butter Feast Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Honey Caramel Container",
      url: "/images/toffee/CARAMAL HONEY2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Caramal Honey Container",
      desc: descriptionObj["HONEY CARAMEL"],
      isGifting: true,
    },
    {
      name: "Coconut Butter Hut Box",
      url: "/images/toffee/COCONUT BUTTER ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Coconut Butter Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Eclairs Anjeer Cream",
      url: "/images/toffee/eclair anjeer cream 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
      desc: descriptionObj["ECLAIRS DARK POUCH"],
    },

    {
      name: "Eclairs Dark Cream",
      url: "/images/toffee/eclair dark cream 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },
    {
      name: "Eclairs Gold Hut Box",
      url: "/images/toffee/ECLAIR GOLD 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Eclair Gold Box",
      brand: "gold",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Eclairs Hazelnut Jar",
      url: "/images/toffee/eclair hazelnut jar 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
    },

    {
      name: "Eclairs Pouch",
      url: "/images/toffee/ECLAIRS POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclairs Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },

    {
      name: "Kesar Creme Hut Box",
      url: "/images/toffee/KESAR CREAM ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Kesar Cream Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },

    {
      name: "Pista Butter Hut Box",
      url: "/images/toffee/PISTA BUTTER BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Pista Butter Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Almond Gold Pouch",
      url: "/images/toffee/ALMOND GOLD POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Almond Gold Pouch",
      brand: "gold",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Butter Feast Hut Box",
      url: "/images/toffee/BUTTER FEAST ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Butter Feast Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Choco Almonds Grand Container",
      url: "/images/toffee/CHOCO ALMOND GRAND 2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Choco Almond Grand Container",
      desc: descriptionObj["HONEY CARAMEL"],
      isGifting: true,
    },
    {
      name: "Dairy Way Hut Box",
      url: "/images/toffee/DAIRY WAY ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Dairy Way Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Eclairs Anjeer Box",
      url: "/images/toffee/eclair anjeer cream gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
    },
    {
      name: "Eclairs Dark Box",
      url: "/images/toffee/eclair dark cream gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
    },

    {
      name: "Eclairs Hut Box",
      url: "/images/toffee/ECLAIRS ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Eclairs Hut Box",
      desc: descriptionObj["ÉCLAIR GOLD"],
    },
    {
      name: "Dryfruit Selections",
      url: "/images/toffee/dry fruit selection gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Dry Fruit Selection Box",
      desc: descriptionObj["SELECTIONS BOX"],
      isGifting: true,
    },
    {
      name: "Eclairs Dark Pouch",
      url: "/images/toffee/eclair dark pouch 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Eclairs Almond Pouch",
      url: "/images/toffee/eclairs carmallos 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Eclairs Hazelnut Pouch",
      url: "/images/toffee/eclair hazelnut pouch 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
    {
      name: "Eclairs Milk Pouch",
      url: "/images/toffee/eclair milk pouch 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
      desc: descriptionObj["BLUE ÉCLAIR POUCH"],
    },
  ],
  jelly: [
    {
      name: "Jellos Strawberry Jelly",
      url: "/images/jelly/STRAWBERRY JELLY.webp",
      price: 1,
      desc: descriptionObj["JELLOS BOX"],
    },
    {
      name: "Jellos Strawberry Jelly Jar",
      url: "/images/jelly/STRAWBERRY JELLY JAR.webp",
      price: 1,
      desc: descriptionObj["JELLOS JAR"],
    },
    {
      name: "Jellos Assorted Jelly",
      url: "/images/jelly/JELLOS MIXFRUIT JELLY.webp",
      price: 1,
      desc: descriptionObj["JELLOS BOX"],
    },
    // {
    //   name: "Jellos Assorted Jelly Jar",
    //   url: "/images/jelly/JELLOS MIX FRUIT JELLY JAR.webp",
    //   price: 1,
    //   desc: descriptionObj["JELLOS JAR"],
    // },
    {
      name: "Jellos Pineapple Jelly",
      url: "/images/jelly/JELLOS PAINAPPLE JELLY.webp",
      price: 1,
      desc: descriptionObj["JELLOS BOX"],
    },
    {
      name: "Jellos Pineapple Jelly Jar",
      url: "/images/jelly/JELLOS JELLY JAR1.webp",
      price: 1,
      desc: descriptionObj["JELLOS JAR"],
    },
    {
      name: "Jellos Guvava Jelly",
      url: "/images/jelly/JELLOS GUVAVA JELLY.webp",
      price: 1,
      desc: descriptionObj["JELLOS BOX"],
    },
    {
      name: "Jellos Guava Jelly Jar",
      url: "/images/jelly/JELLOS GUVAVA JELLY JAR.webp",
      price: 1,
      desc: descriptionObj["JELLOS JAR"],
    },
    {
      name: "Jellos Mango Jelly",
      url: "/images/jelly/JELLOS MANGO JELLY.webp",
      price: 1,
      desc: descriptionObj["JELLOS BOX"],
    },
    {
      name: "Jellos Mango Jelly Jar",
      url: "/images/jelly/JELLOS MANGO JELLY JAR.webp",
      price: 1,
      desc: descriptionObj["JELLOS JAR"],
    },
    {
      name: "Jellos Mix Fruit Jelly",
      url: "/images/jelly/JELLOS JELLY.webp",
      price: 1,
      desc: descriptionObj["JELLOS BOX"],
    },

    // {
    //   name: "Jellos Pineapple Jar",
    //   url: "/images/jelly/JELLOS JELLY JAR.webp",
    //   price: 1,
    //   desc: descriptionObj["JELLOS JAR"],
    // },
  ],
  candy: [
    {
      name: "Double Berry",
      url: "/images/candy/DOUBLE BERRY RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Berry",
      desc: descriptionObj["DOUBLE STRAWBERRY"],
    },
    {
      name: "Double Coconut",
      url: "/images/candy/DOUBLE COCONUT RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Coconut",
      desc: descriptionObj["DOUBLE STRAWBERRY"],
    },
    {
      name: "Double Kaccha Aam",
      url: "/images/candy/DOUBLE KACCHA AAM RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Kaccha Aam",
      desc: descriptionObj["DOUBLE STRAWBERRY"],
    },
    {
      name: "Double Mango",
      url: "/images/candy/DOUBLE MANGO RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Mango",
      brand: "double mango",
      desc: descriptionObj["DOUBLE STRAWBERRY"],
    },
    {
      name: "Choco Orange",
      url: "/images/candy/DOUBLE ORANGE RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Orange",
      desc: descriptionObj["DOUBLE STRAWBERRY"],
    },
    {
      name: "Double Guava",
      url: "/images/candy/DOUBLE GUVAVA RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Guvava",
      desc: descriptionObj["DOUBLE STRAWBERRY"],
    },
    {
      name: "Double Paan",
      url: "/images/candy/DOUBLE PAAN RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Paan",
      brand: "double paan",
      desc: descriptionObj["DOUBLE STRAWBERRY"],
    },
    {
      name: "Kisszone 167 Pcs",
      url: "/images/candy/KISSZONE02 1RS.webp",

      price: 1,
      category: "Pouch",
      subCategory: "Kisszone 165Pcs",
      brand: "kiss zone",
      desc: descriptionObj["KISSZONE ASSORTED"],
    },
    {
      name: "Kisszone",
      url: "/images/candy/KISSZONE01 1RS.webp",
      price: 1,
      brand: "kiss zone",
    },
    {
      name: "Kisszone 50 Pcs",
      url: "/images/candy/KISSZONE RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Kisszone 50pcs",
      brand: "kiss zone",
      desc: descriptionObj["KISSZONE 50 PCS SMALL"],
    },
    {
      name: "Beating Heart",
      url: "/images/candy/BEATING HEART RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Beating Heart",
      desc: descriptionObj["KISSZONE ASSORTED"],
    },
    {
      name: "Kisszone Dark",
      url: "/images/candy/KISSZONE DARK RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Kisszone Dark",
      brand: "kiss zone",
      desc: descriptionObj["KISSZONE ASSORTED"],
    },
    {
      name: "Pan Meetha",
      url: "/images/candy/PAN MEETHA 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Pan Meetha",
      desc: descriptionObj["KISSZONE ASSORTED"],
    },
    {
      name: "Tambley",
      url: "/images/candy/TAMBLEY 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Tambley",
      desc: descriptionObj["KISSZONE ASSORTED"],
    },
    {
      name: "Kacche Aam",
      url: "/images/candy/KACHA AAM CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "Kacha Aam Candy",
      desc: descriptionObj["LONDON COW"],
    },
    {
      name: "London Cow",
      url: "/images/candy/LONDONCOW RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Londoncow",
      desc: descriptionObj["LONDON COW"],
    },
    {
      name: "Oranja",
      url: "/images/candy/ORAGE RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Orage",
      desc: descriptionObj["LONDON COW"],
    },
    {
      name: "Fruit Bon Bon ",
      url: "/images/candy/FRUIT BON BON 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "Fruit Bon Bon",
      desc: descriptionObj["LONDON COW"],
    },
    {
      name: "Fruits Candy",
      url: "/images/candy/FRUITS CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
      desc: descriptionObj["GUAVA"],
    },
    {
      name: "Imli Candy",
      url: "/images/candy/IMLI CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
      desc: descriptionObj["GUAVA"],
    },
    {
      name: "Mango Candy",
      url: "/images/candy/MANGO CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
      desc: descriptionObj["GUAVA"],
    },
    {
      name: "Orange Candy",
      url: "/images/candy/ORNGE CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
      desc: descriptionObj["GUAVA"],
    },

    {
      name: "Pineapple Candy",
      url: "/images/candy/PINEAPPLE CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
      desc: descriptionObj["GUAVA"],
    },
    {
      name: "Strawberry Candy",
      url: "/images/candy/STRAWBERRY CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
      desc: descriptionObj["GUAVA"],
    },
    {
      name: "Kacha Aam",
      url: "/images/candy/KACHA AAM 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
    },
    {
      name: "Double Mango Jar ",
      url: "/images/centerMissing/Double Mango .webp",
      price: 0.5,
      category: "Jar",
      subCategory: "Double Mango Jar",
      brand: "double mango",
      desc: descriptionObj["Double Mango Jar"],
    },
    {
      name: "D-BON Coconut Jar ",
      url: "/images/jarleft/D-BON COCONUT.png",
      price: 0.5,
      category: "Jar",
      subCategory: "D-BON Coconut Jar",
      brand: "double mango",
      desc: descriptionObj["D-BON Coconut Jar"],
    },
    {
      name: "D-BON Guava Jar ",
      url: "/images/jarleft/D-BON GUAVA.png",
      price: 0.5,
      category: "Jar",
      subCategory: "D-BON Coconut Jar",
      brand: "double mango",
    },
    {
      name: "D-BON Mango Jar ",
      url: "/images/jarleft/D-BON MANGO.png",
      price: 0.5,
      category: "Jar",
      subCategory: "D-BON Coconut Jar",
      brand: "double mango",
    },
    {
      name: "D-BON Orange Jar ",
      url: "/images/jarleft/D-BON ORANGE.png",
      price: 0.5,
      category: "Jar",
      subCategory: "D-BON Coconut Jar",
      brand: "double mango",
    },
    {
      name: "D-BON Pineapple Jar ",
      url: "/images/jarleft/D-BON PINEAPPLE.png",
      price: 0.5,
      category: "Jar",
      subCategory: "D-BON Coconut Jar",
      brand: "double mango",
    },
    {
      name: "Double Strawberry Jar ",
      url: "/images/jarleft/D-BON STRAWBERRY.png",
      price: 0.5,
      category: "Jar",
      subCategory: "D-BON Coconut Jar",
      brand: "double mango",
    },
  ],

  lollipop: [
    {
      name: "Frugo Pop Stand",
      url: "/images/lollipop/Fru Go Pop.webp",
      price: 5,
      desc: descriptionObj["FRUGO POP STAND"],
    },
    {
      name: "Frudoza Container",
      url: "/images/lollipop/Frudoza.webp",
      price: 5,
      desc: descriptionObj["FRUDOZA CONT"],
    },
    {
      name: "Frugo Pop Jar",
      url: "/images/lollipop/Frugo Pop Jar.webp",
      price: 5,
      desc: descriptionObj["FRUGO POP JAR"],
    },
    {
      name: "Frugo Pop Pouch",
      url: "/images/lollipop/Frugo Pop Pouch.webp",
      price: 5,
      desc: descriptionObj["FRUGO POP POUCH"],
    },
    {
      name: "Frutos Pops Jar",
      url: "/images/lollipop/FRUTOS LOLLIPOP JAR.webp",
      price: 5,
      desc: descriptionObj["FRUTOS POP JAR"],
    },
    {
      name: "Lolly Pouch",
      url: "/images/lollipop/LOLLY LOLLIPOP  POUCH.webp",
      price: 5,
      desc: descriptionObj["LOLLY POUCH"],
    },
    {
      name: "Lolly Container",
      url: "/images/lollipop/LOLLY LOLLIPOP.webp",
      price: 5,
      desc: descriptionObj["LOLLY CONT"],
    },
    {
      name: "Tammy Pop Container",
      url: "/images/centerMissing/TAMMY POP CONTAINER.png",
      price: 5,

      desc: descriptionObj["TAMMY POP CONT"],
    },
  ],
};

export default productObj;
