export type productType = {
  [key: string]: {
    name: string;
    url: string;
    price?: number;
    category?: string;
    subCategory?: string;
    description?: string;
    brand?: string;
  }[];
};

export const productObj: productType = {
  "chocolate bar": [
    {
      name: "Cocoa Milk Chocolate Bar",
      url: "/images/chocolatebar/Cocoa Milk Choclate Bar.webp",
      price: 1,
    },
    {
      name: "Dairy Kiss Cocoa",
      url: "/images/centerMissing/Dairy Kiss Milk Cocoa.webp",
      price: 5,
      brand: "dairy kiss",
    },
    {
      name: "Dairy Kiss Container",
      url: "/images/centerMissing/Dairy Kiss Container.webp",
      price: 5,
      brand: "dairy kiss",
    },
    {
      name: "StrawBerry Bar",
      url: "/images/chocolatebar/StrawBerry Bar.webp",
      price: 5,
    },
    {
      name: "Black & White Bar",
      url: "/images/chocolatebar/Black & White Bar.webp",
      price: 5,
      category: "c-1",
    },
    {
      name: "Milkies Milk Choclate Bar",
      url: "/images/chocolatebar/Milkies Milk Choclate Bar.webp",
      price: 5,
    },
    {
      name: "Coconut Bar",
      url: "/images/chocolatebar/Coconut Bar.webp",
      price: 5,
    },

    {
      name: "Dark Milk Chocolate Bar",
      url: "/images/chocolatebar/Dark Milk Choclate Bar.webp",
      price: 5,
    },
    {
      name: "Milk Chocolate Bar",
      url: "/images/chocolatebar/Milk Choclate Bar.webp",
      price: 5,
    },
    {
      name: "HazelNut Bar",
      url: "/images/chocolatebar/HazelNut Bar.webp",
      price: 5,
    },
    {
      name: "Dairy KIss Cocoa",
      url: "/images/centerMissing/Dairy Kiss Milk Cocoa.webp",
      price: 5,
      brand: "dairy kiss",
    },
    {
      name: "Dairy KIss Milkies",
      url: "/images/centerMissing/Dairy Kiss Milk Box.webp",
      price: 5,
      brand: "dairy kiss",
    },
    {
      name: "Safari Park",
      url: "/images/chocolatebar/Safari Park.webp",
      price: 2,
    },
  ],
  "centerfilled chocolate": [
    {
      name: "Truffles Milk 70 pcs",
      url: "/images/centerfilledchocolate/TRUFFLE MILK 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Blueberry 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE BLUBERRY 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffles Milk",
      url: "/images/centerfilledchocolate/TRUFFLES MILK GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Blue Berry",
      url: "/images/centerfilledchocolate/TRUFFLE BLUE BERRY GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Milk",
      url: "/images/centerfilledchocolate/TRUFFLE MILK 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffle Bueberry",
      url: "/images/centerfilledchocolate/TRUFFLE BUEBERRY 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffles Pouch",
      url: "/images/centerfilledchocolate/TRUFFLES BLUE POUCH 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles Pouch",
      brand: "truffle",
    },
    {
      name: "Truffle 30 Pcs Container",
      url: "/images/centerfilledchocolate/TRUFFLE CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 30 Pcs Container",
      brand: "truffle",
    },
    {
      name: "Truffle Container",
      url: "/images/centerfilledchocolate/TRUFFLE GIFT CONTAIER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 30 Pcs Container",
      brand: "truffle",
    },
    {
      name: "Truffle Milk 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE MILK 70 PCS 5RS.webp",
      price: 5,
      brand: "truffle",
    },
    {
      name: "Truffle Pistachio 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE PISTACHIO 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Pistachio 150 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE PISTACHIO 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffle Rajbhog 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE RAJBHOG 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Rajbhog",
      url: "/images/centerfilledchocolate/TRUFFLE RAJBHOG 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffle Rajbhog",
      url: "/images/centerfilledchocolate/TRUFFLE RAJBHOG GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Strawberry 70 Pcs",
      url: "/images/centerfilledchocolate/TRUFFLE STRAWBERRY 70 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 pcs",
      brand: "truffle",
    },
    {
      name: "Truffle Strawberry",
      url: "/images/centerfilledchocolate/TRUFFLE STRAWBERRY 150 PCS 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 2kg",
      brand: "truffle",
    },
    {
      name: "Truffles 70 Pcs Container",
      url: "/images/centerfilledchocolate/TRUFFLES CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 Pcs Container",
      brand: "truffle",
    },
    {
      name: "Truffles 70 Pcs Container",
      url: "/images/centerfilledchocolate/TRUFFLES CONTAINER 2 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 70 Pcs Container",
      brand: "truffle",
    },
    {
      name: "Truffles Pouch",
      url: "/images/centerfilledchocolate/TRUFFLES RED POUCH 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles Pouch",
      brand: "truffle",
    },
    {
      name: "Truffles Strawberry",
      url: "/images/centerfilledchocolate/TRUFFLES STRAWBERRY GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },
    {
      name: "Truffles Pistachio",
      url: "/images/centerfilledchocolate/TRUFFLES PISTACHIO GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Truffles 20 pcs",
      brand: "truffle",
    },

    {
      name: "Dlove Gold 70Pcs Box",
      url: "/images/centerfilledchocolate/DLOVE GOLD 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 70Pcs Box",
      brand: "d love",
    },
    {
      name: "Dlove Gold Pouch",
      url: "/images/centerfilledchocolate/DLOVE GOLD POUCH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold Pouch",
      brand: "d love",
    },
    {
      name: "Dlove Gold 30Pcs Container",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 30Pcs Container",
      brand: "d love",
    },
    {
      name: "Dlove Gold 40Pcs Container",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 40Pcs Container",
      brand: "d love",
    },
    {
      name: "Dlove Gold 2Kg Box",
      url: "/images/centerMissing/D'Love Gold.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Gold 2Kg Box",
      brand: "d love",
    },
    {
      name: "Dlove Purple",
      url: "/images/centerfilledchocolate/DLOVE PURPULE 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel 70Pcs Box",
      brand: "d love",
    },

    {
      name: "Dlove Container",
      url: "/images/centerfilledchocolate/DLOVE CONTAINER 5RS.webp",
      price: 5,
      brand: "d love",
    },
    {
      name: "Dlove Green",
      url: "/images/centerfilledchocolate/DLOVE GREEN5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel 70Pcs Box",
      brand: "d love",
    },
    {
      name: "Dlove Pink",
      url: "/images/centerMissing/D'Love Pink.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel 70Pcs Box",
      brand: "d love",
    },
    {
      name: "Dlove Pastel Pouch",
      url: "/images/centerfilledchocolate/DLOVE GREEN POUH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel Pouch",
      brand: "d love",
    },
    {
      name: "Dlove Pink Pouch",
      url: "/images/centerfilledchocolate/DLOVE PINK POUCH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Pastel Pouch",
      brand: "d love",
    },
    {
      name: "Dlove Red 70Pcs Box",
      url: "/images/centerfilledchocolate/DLOVE RED 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Red 70Pcs Box",
      brand: "d love",
    },
    {
      name: "Dlove Red Jar",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Dlove Red Jar",
      brand: "d love",
    },
    {
      name: "Amore 70Pcs Box",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Amore 70Pcs Box",
    },
    {
      name: "Amore 30Pcs Container",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Amore 30Pcs Container",
    },
    {
      name: "Delight Pistachio 70Pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT PISTACGIO 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
    },

    {
      name: "Delight Rajbhog 70Pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT RAJBHOG 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
    },

    {
      name: "Delight Strawberry 70Pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT STRAWBERRY 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
    },
    {
      name: "Delight Cashewnut 70pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT CAHEWNUT 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
    },
    {
      name: "Delight Mango 70pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT MANGO 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
    },

    {
      name: "Delight Pistachio 150Pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT PISTACHIO 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Delight Rajbhog 150Pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT RAJBHOG 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Delight Strawberry 150Pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT STRAWBERRY150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Delight Mango 150pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT MANGO150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },

    {
      name: "Delight Blueberry 150pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT BLUEBERRY 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Cocos 70pcs Box",
      url: "/images/centerfilledchocolate/COCOS  TRUFFLES BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Cocos 70pcs Box",
      brand: "cocos",
    },

    {
      name: "Cocos Pouch",
      url: "/images/centerfilledchocolate/COCOS  TRUFFLES POUCH 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Cocos Pouch",
      brand: "cocos",
    },
    {
      name: "Bliss Dark 125pcs Box",
      url: "/images/centerfilledchocolate/BLISS DARK 1RS.webp",
      price: 1,
      category: "Pillow Pack",
      subCategory: "Bliss 125pcs Box",
    },

    {
      name: "Bliss strawberry 125pcs Box",
      url: "/images/centerfilledchocolate/BLISS STRAWBERRY 1RS.webp",
      price: 1,
      category: "Pillow Pack",
      subCategory: "Bliss 125pcs Box",
    },

    {
      name: "Bliss white 125pcs Box",
      url: "/images/centerfilledchocolate/BLISS WHITE 1RS.webp",
      price: 1,
      category: "Pillow Pack",
      subCategory: "Bliss 125pcs Box",
    },
    {
      name: "Gold 125Pcs Box",
      url: "/images/centerfilledchocolate/GOLD GIFTBOX2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Gold 125Pcs Box",
      brand: "gold",
    },
    {
      name: "Gold 125Pcs Box",
      url: "/images/centerfilledchocolate/GOLD GIFT BOX2RS 2.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Gold 125Pcs Box",
      brand: "gold",
    },
    {
      name: "Emporio 70Pcs Box",
      url: "/images/centerfilledchocolate/EMPORIO 70PCS BOX 5RS.webp",
      price: 5,
      brand: "emporio",
    },
    {
      name: "Emporio Pouch",
      url: "/images/centerfilledchocolate/EMPORIO POUCH  5RS.webp",
      price: 5,
      brand: "emporio",
    },
    {
      name: "Empirio Box",
      url: "/images/centerfilledchocolate/EMPIRIO BOX 5RS.webp",
      price: 5,
      brand: "emporio",
    },
    {
      name: "DGold 60Pcs Box",
      url: "/images/centerfilledchocolate/GOLD BOX2RS 2.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "DGold 60Pcs Box",
    },

    {
      name: "DGold 60Pcs Box",
      url: "/images/centerfilledchocolate/GOLD BOX2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "DGold 60Pcs Box",
    },
    {
      name: "Endon 60Pcs Box",
      url: "/images/centerfilledchocolate/ENDON GIFT BOX 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 60Pcs Box",
      brand: "endon",
    },

    {
      name: "Endon 60Pcs Box",
      url: "/images/centerfilledchocolate/ENDON GOFT BOX1 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 60Pcs Box",
      brand: "endon",
    },
    {
      name: "Endon 125Pcs Box",
      url: "/images/centerfilledchocolate/ENDON BOX 125 PCS 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 125Pcs Box",
      brand: "endon",
    },
    {
      name: "Endon 125Pcs Box",
      url: "/images/centerfilledchocolate/ENDON BOX 125 PCS2 2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Endon 125Pcs Box",
      brand: "endon",
    },
    {
      name: "Glorious Pistachio",
      url: "/images/centerfilledchocolate/GLORIOUS PISTACHIO5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
    },
    {
      name: "Glorious Chocolate",
      url: "/images/centerfilledchocolate/GLORIOUS CHOCOLATE 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
    },
    {
      name: "Glorious Gift Box",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious Gift Box",
    },
    {
      name: "Glorious Cashewnut 2Kg Box",
      url: "/images/centerMissing/Glorious Cashewnut.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
    },
    {
      name: "Glorious Chocolait 2Kg Box",
      url: "/images/centerMissing/Glorious Chocolait.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
    },
    {
      name: "Glorious Milk 2Kg Box",
      url: "/images/centerMissing/Glorious Milk.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
    },
    {
      name: "Glorious Pistachio 2Kg Box",
      url: "/images/centerMissing/Glorious Pistachio.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
    },
    {
      name: "Glorious Rajbhog 2Kg Box",
      url: "/images/centerMissing/Glorious Rajbhog.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 2Kg Box",
    },
    // {
    //   name: "Glorious Cashewnut",
    //   url: "/images/centerfilledchocolate/GLORIOUS CCASHEWNUT 5RS.webp",
    //   price: 5,
    //   category: "Single Twist",
    //   subCategory: "Glorious 70 pcs",
    // },
    {
      name: "Glorious 30Pcs Container",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 30Pcs Container",
    },
    {
      name: "Glorious 30Pcs Container",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT CONTAINER (2) 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 30Pcs Container",
    },
    {
      name: "Glorious 30Pcs Container",
      url: "/images/centerfilledchocolate/GLORIOUS GIFT CONTAINER (3) 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 30Pcs Container",
    },
    {
      name: "Glorious Milk",
      url: "/images/centerfilledchocolate/GLORIOUS MILK 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
    },
    {
      name: "Glorious Raajbhog",
      url: "/images/centerfilledchocolate/GLORIOUS RAAJBHOG 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Glorious 70 pcs",
    },

    {
      name: "Gold Box",
      url: "/images/centerfilledchocolate/GOLD GIFT BOX 2RS.webp",
      price: 2,
      category: "Bunch Rape",
      subCategory: "Gold Box",
      brand: "gold",
    },
    {
      name: "Gold Jar",
      url: "/images/centerfilledchocolate/GOLD ROUND JAR 2RS.webp",
      price: 2,
      category: "Bunch Rape",
      subCategory: "Gold Jar",
      brand: "gold",
    },
    {
      name: "United Box",
      url: "/images/centerfilledchocolate/UNITED GIFT BOX 2RS.webp",
      price: 2,
      category: "Bunch Rape",
      subCategory: "United Box",
    },
    {
      name: "United Jar",
      url: "/images/centerfilledchocolate/UNITED JAR 2RS.webp",
      price: 2,
      category: "Bunch Rape",
      subCategory: "United Jar",
    },
    {
      name: "DLove Jar",
      url: "/images/DAZZY LOGO.webp",
      price: 2,
      category: "Bunch Rape",
      subCategory: "DLove Jar",
    },
    {
      name: "Stacy 20Pcs Box",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS 1.webp",
      price: 5,
    },

    {
      name: "D Love Gold 150 Pcs",
      url: "/images/centerfilledchocolate/D LOVE GOLD 150 PCS 5RS.webp",
      price: 5,
      brand: "d love",
    },
    {
      name: "Delight Cashewnuut 150pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT CASHEWNUUT 150PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 2Kg Box",
    },
    {
      name: "Merone 125pcs Box",
      url: "/images/centerfilledchocolate/MERONE 125PCS  2RS.webp",
      price: 2,
      category: "Pillow Pack",
      subCategory: "Merone 125pcs Box",
    },
    {
      name: "Stacy Chocolate Container",
      url: "/images/centerfilledchocolate/STACY CHOCOLATE CANTAINER  5RS.webp",
      price: 5,
    },
    {
      name: "Stacy Box",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS 2  5RS.webp",
      price: 5,
    },
    {
      name: "Stacy Gift Container",
      url: "/images/centerfilledchocolate/STACY GIFT CONTAINER  5RS.webp",
      price: 5,
    },

    {
      name: "Boliva Container",
      url: "/images/centerfilledchocolate/BOLIVA CONTAINER 5RS.webp",
      price: 5,
    },
    {
      name: "Bolivia 150 Pcs Box",
      url: "/images/centerfilledchocolate/BOLIVIA150 PCS BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 150 Pcs Box",
      brand: "bolivia",
    },

    {
      name: "Delight Blueberry 70pcs Box",
      url: "/images/centerfilledchocolate/DELIGHT BLUEBERRY 70PCS BOX 5RS.webp",
      price: 5,
      category: "Pillow Pack",
      subCategory: "Delight 70pcs Box",
    },

    {
      name: "Stacy 70pcs Box",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 70pcs",
    },
    {
      name: "Stacy Box 70pcs ",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS 2  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 70pcs",
    },
    {
      name: "Stacy Box 70pcs ",
      url: "/images/centerfilledchocolate/STACY BOX 70PCS 1.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 70pcs",
    },
    {
      name: "Stacy Box 20pcs ",
      url: "/images/centerfilledchocolate/STACY GIFT BOX 1  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 20pcs",
    },
    {
      name: "Stacy Box 20pcs ",
      url: "/images/centerfilledchocolate/STACY GIFT BOX 2  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 20pcs",
    },
    {
      name: "Stacy Box 20pcs ",
      url: "/images/centerfilledchocolate/STACY GIFT BOX  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Box 20pcs",
    },
    {
      name: "Stacy Container",
      url: "/images/centerfilledchocolate/STACY CONTAINER  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Stacy Container",
    },
    {
      name: "Stacy Gift Box",
      url: "/images/centerfilledchocolate/STACY GIFT BOX  5RS.webp",
      price: 5,
    },

    {
      name: "Bolivia 70 Pcs Box",
      url: "/images/centerfilledchocolate/BOLIVIA 70 PCS BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 70 Pcs Box",
      brand: "bolivia",
    },
    {
      name: "Bolivia 25Pcs Box",
      url: "/images/centerfilledchocolate/BOLIVIA GIFT BOX 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 25Pcs Box",
      brand: "bolivia",
    },

    {
      name: "Chocobon Container",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Container",
      brand: "choco bon",
    },
    {
      name: "Chocobon Pistachio",
      url: "/images/centerfilledchocolate/CHOCOBON PISTACHIO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
    },

    {
      name: "Chocobon Coconut",
      url: "/images/centerfilledchocolate/CHOCOBON COCONUT  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
    },
    {
      name: "Chocobon Strawberry",
      url: "/images/centerfilledchocolate/CHOCOBON STRAWBERRY  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
    },
    {
      name: "Chocobon Mango",
      url: "/images/centerfilledchocolate/CHOCOBON MANGO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
      brand: "choco bon",
    },
    {
      name: "Ferola Milk",
      url: "/images/centerfilledchocolate/FEROLA MILK  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
    },
    {
      name: "Ferola Coconut",
      url: "/images/centerfilledchocolate/FEROLA COCONUT  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
    },
    {
      name: "Ferola Mango",
      url: "/images/centerfilledchocolate/FEROLA MANGO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
    },
    {
      name: "Ferola Pistachio",
      url: "/images/centerfilledchocolate/FEROLA PISTACHIO  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
    },
    {
      name: "Ferola Strawberry",
      url: "/images/centerfilledchocolate/FEROLA STRAWBERRY  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Box",
    },
    {
      name: "Ferola 70pcs Container",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Ferola 70Pcs Container",
    },
    {
      name: "Stacy Mini MatkaJar",
      url: "/images/centerfilledchocolate/STACY MINIS JAR 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Mini MatkaJar",
    },
    {
      name: "Stacy Minis Container",
      url: "/images/centerfilledchocolate/STACY MINIS CONTAINER 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Mini Container",
    },
    {
      name: "Stacy Minis 50Pcs Box",
      url: "/images/centerfilledchocolate/STACY MINIS GIFT BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Minis 50Pcs Box",
    },
    {
      name: "Stacy Minis 125 Pcs Box",
      url: "/images/centerfilledchocolate/STACY MINIS 125 PCS BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Stacy Minis 125 Pcs Box",
    },
    {
      name: "Brevo 50Pcs Box",
      url: "/images/centerfilledchocolate/BREVO GIFT BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Brevo 50Pcs Box",
    },

    {
      name: "Brevo 125Pcs Box",
      url: "/images/centerfilledchocolate/BREVO 125 PCS BOX 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Brevo 125Pcs Box",
    },
    {
      name: "Brevo Container",
      url: "/images/centerfilledchocolate/BREVO CONTAINER 2RS.webp",
      price: 2,
      category: "Double Twist",
      subCategory: "Brevo Container",
    },

    {
      name: "Bolivia 70Pcs Container",
      url: "/images/centerfilledchocolate/BOLIVIA CONTAINER 5RS.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia 70Pcs Container",
      brand: "bolivia",
    },
    {
      name: "Bolivia 30Pcs Container",
      url: "/images/centerMissing/Bolivia Container.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Bolivia Container",
      brand: "bolivia",
    },
    {
      name: "Chocobon Milk",
      url: "/images/centerfilledchocolate/CHOCOBON MILK  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Chocobon 70Pcs Box",
    },
    {
      name: "Truffles 30 Pcs",
      url: "/images/centerfilledchocolate/TRUFFINS 30 PCS 5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffles 30 Pcs",
    },
    {
      name: "Truffles 30 Pcs",
      url: "/images/centerfilledchocolate/TRUFFINS 30 PCS 1  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffles 30 Pcs",
    },
    {
      name: "Truffins 70Pcs Box",
      url: "/images/centerfilledchocolate/TRUFFINS 70 PCS  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffins 70Pcs Box",
    },
    {
      name: "Truffins 70Pcs Box",
      url: "/images/centerfilledchocolate/TRUFFINS 70 PCS 1  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffins 70Pcs Box",
    },
    {
      name: "Truffins Container",
      url: "/images/centerfilledchocolate/TRUFFINS CONTAINER  5RS.webp",
      price: 5,
      category: "Double Twist",
      subCategory: "Truffins Container",
    },

    {
      name: "Orientto Coconut 70Pcs Box",
      url: "/images/centerMissing/Orientto Coconut.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
    },
    {
      name: "Orientto Hazalnut 70Pcs Box",
      url: "/images/centerMissing/Orientto Hazalnut.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
    },
    {
      name: "Orientto Pista 70Pcs Box",
      url: "/images/centerMissing/Orientto Pista .webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
    },
    {
      name: "Orientto Pista 70Pcs Box",
      url: "/images/centerMissing/Orientto Pista .webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
    },
    {
      name: "Orientto Strwberry 70Pcs Box",
      url: "/images/centerMissing/Orientto Strwberry.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 70Pcs Box",
    },
    // {
    //   name: "Oriento 2Kg Box",
    //   url: "/images/centerfilledchocolate/GLORIOUS GIFT BOX 253RS.webp",
    //   price: 5,
    //   category: "Single Twist",
    //   subCategory: "Oriento 2Kg Box",
    // },
    {
      name: "Oriento 30pcs Container",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
      category: "Single Twist",
      subCategory: "Oriento 30pcs Container",
    },
    {
      name: "Maxic Box 125 Pcs",
      url: "/images/centerfilledchocolate/MAXIC  BOX 125 PCS 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Maxic Box 125 Pcs",
    },
    {
      name: "Maxic 50Pcs Box",
      url: "/images/centerfilledchocolate/MAXIC GIFT BOX 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Maxic 50Pcs Box",
    },
    {
      name: "Belgium 125 Pcs Box",
      url: "/images/centerfilledchocolate/BELGIUM 125 PCS 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Belgium 125 Pcs Box",
    },
    {
      name: "Belgiam 50Pcs Box",
      url: "/images/centerfilledchocolate/BELGIAM GIFT BOX 2RS.webp",
      price: 2,
      category: "Single Twist",
      subCategory: "Belgiam 50Pcs Box",
    },
  ],
  "decorative chocolate": [
    {
      name: "King Kong",
      url: "/images/decorativechocolate/KING KONG 1 5RS.webp",
      price: 5,
    },

    {
      name: "King Kong",
      url: "/images/decorativechocolate/KING KONG 5RS.webp",
      price: 5,
    },
    {
      name: "Dr Teddy",
      url: "/images/decorativechocolate/DR TEDDY5RS.webp",
      price: 5,
      brand: "dr. teddy",
    },
    {
      name: "Dr Teddy",
      url: "/images/decorativechocolate/DR TEDDY25RS.webp",
      price: 25,
      brand: "dr. teddy",
    },

    {
      name: "Choco Tocon 10RS",
      url: "/images/decorativechocolate/CHOCO TOCON 10RS.webp",
      price: 10,
    },
    {
      name: "Choco COAN 5RS",
      url: "/images/decorativechocolate/CHOCO COAN 5RS.webp",
      price: 5,
    },
  ],
  "Crunchy chocolate": [
    {
      name: "Oh Wow Big Box",
      url: "/images/peanut chocolate/OH WOW BIG BOX.webp",
      price: 5,
      brand: "oh! wow",
    },
    {
      name: "Oh Wow Pouch",
      url: "/images/peanut chocolate/OH WOW POUCH.webp",
      price: 2,
      brand: "oh! wow",
    },
    {
      name: "Oh Wow Small Box",
      url: "/images/peanut chocolate/OH WOW SMALL BOX.webp",
      price: 2,
      brand: "oh! wow",
    },
    {
      name: "Oh Wow Standy Pouch",
      url: "/images/peanut chocolate/OH WOW STANDY POUCH.webp",
      price: 2,
      brand: "oh! wow",
    },
    {
      name: "Caranut Box",
      url: "/images/peanut chocolate/CARANUT BOX.webp",
      price: 5,
    },
    {
      name: "Chokers Box",
      url: "/images/peanut chocolate/CHOKERS BOX.webp",
      price: 5,
    },
    {
      name: "Chokers Container",
      url: "/images/peanut chocolate/CHOKERS CONTAINER.webp",
      price: 5,
    },
  ],
  "nought bar": [
    {
      name: "BIG STAR",
      url: "/images/nugut bar/BIG STAR.webp",
      price: 5,
      brand: "big star",
    },
    {
      name: "BIG STAR BOX",
      url: "/images/nugut bar/BIG STAR BOX.webp",
      price: 5,
      brand: "big star",
    },
    {
      name: "Chockers Container",
      url: "/images/nugut bar/CHOKERS CONTAINER 5RS.webp",
      price: 5,
    },
    {
      name: "Chockers Box",
      url: "/images/nugut bar/CHOKERS BOX5RS.webp",
      price: 5,
    },
    {
      name: "TORNUTTE  BAR CONTAINER",
      url: "/images/nugut bar/TORNUTTE  BAR CONTAINER.webp",
      price: 5,
    },
    {
      name: "TORNUTTE  BAR BOX",
      url: "/images/nugut bar/TORNUTTE  BAR BOX.webp",
      price: 5,
    },

    {
      name: "Caramet Cont",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
    },
    {
      name: "Carafians Cont ",
      url: "/images/DAZZY LOGO.webp",
      price: 5,
    },
    {
      name: "BRACKERS BOX",
      url: "/images/nugut bar/BRACKERS BOX.webp",
      price: 5,
    },
  ],

  "wafer rolls": [
    {
      name: "3 Stix Chocofills",
      url: "/images/wafffer rolls/3 stix chocofills.webp",
      price: 5,
      brand: "3 stix",
    },
    {
      name: "3stix Milk Fills",
      url: "/images/wafffer rolls/3stix milk fills.webp",
      price: 5,
      brand: "3 stix",
    },
    {
      name: "3 Stix Kraks",
      url: "/images/wafffer rolls/3 stix kraks.webp",
      price: 5,
      brand: "3 stix",
    },

    {
      name: "Big Roll Chocolate",
      url: "/images/wafffer rolls/big roll chocolate.webp",
      price: 5,
      brand: "big rolle",
    },
    {
      name: "Big Roll Dark",
      url: "/images/wafffer rolls/big roll dark.webp",
      price: 5,
      brand: "big rolle",
    },
    {
      name: "Big Roll Milk",
      url: "/images/wafffer rolls/big roll milk.webp",
      price: 5,
      brand: "big rolle",
    },
    {
      name: "Choco Stix",
      url: "/images/wafffer rolls/choco stix.webp",
      price: 5,
      brand: "3 stix",
    },

    {
      name: "Rolle Stix",
      url: "/images/wafffer rolls/rolle stix.webp",
      price: 5,
      brand: "3 stix",
    },
    {
      name: "Dark Stix",
      url: "/images/wafffer rolls/dark stix.webp",
      price: 5,
      brand: "3 stix",
    },
    {
      name: "Krack Stix",
      url: "/images/wafffer rolls/krack stix.webp",
      price: 5,
      brand: "3 stix",
    },

    {
      name: "Wafeer Roll",
      url: "/images/wafffer rolls/wafeer roll.webp",
      price: 5,
    },
  ],
  toffee: [
    {
      name: "Eclair Coconut Cream",
      url: "/images/toffee/eclair coconut cream 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },
    {
      name: "Cocotana Pouch",
      url: "/images/toffee/Cocotana Pouch.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Cocotana Pouch",
    },
    {
      name: "Dry Fruit Selection Gift Pouch",
      url: "/images/toffee/dry fruit selection gift pouch 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Dry Fruit Selection Gift Pouch",
    },
    {
      name: "Malai Kulfi jar",
      url: "/images/toffee/malai kulfi 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Malai Kulfi jar",
    },
    {
      name: "Malai Kulfi Coconut Jar",
      url: "/images/toffee/MALAI KULFI COCONUT JAR RS1.webp",
      price: 1,
      category: "Jar",
      subCategory: "Malai Kulfi Coconut Jar",
    },
    {
      name: "Malai Kulfi Kesar Kaju Jar",
      url: "/images/toffee/MALAI KULFI KESAR KAJU JAR RS1.webp",
      price: 1,
      category: "Jar",
      subCategory: "Malai Kulfi Kesar Kaju Jar",
    },
    {
      name: "Soffitti Jar",
      url: "/images/toffee/soffiti 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Soffitti Jar ",
    },
    {
      name: "Natural Jar",
      url: "/images/toffee/NATURAL JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Natural Jar",
    },
    {
      name: "Eclair Gold Jar",
      url: "/images/toffee/ECLAIR GOLD JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair Gold Jar",
      brand: "gold",
    },
    {
      name: "Kaju Butter Jar",
      url: "/images/toffee/KAJU BUTTER JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Kaju Butter Jar",
    },
    {
      name: "Pista Butter Jar",
      url: "/images/toffee/PISTA BUTTER JAR 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Pista Butter Jar",
    },

    {
      name: "Kaju Butter Pouch",
      url: "/images/toffee/KAJU BUTTER POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Kaju Butter Pouch",
    },

    {
      name: "Natural Pouch",
      url: "/images/toffee/NATURAL POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Natural Pouch",
    },

    {
      name: "Swiss Dairy Hut Box",
      url: "/images/toffee/SWISS DAIRY ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Swiss Dairy Hut Box",
    },
    {
      name: "Almond Hut Box",
      url: "/images/toffee/ALMOND ZUPADI  BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Almond Hut Box ",
    },
    {
      name: "Butterscotch Hut Box",
      url: "/images/toffee/BUTTER SCOTCH ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Butterscotch Hut Box",
    },
    {
      name: "Cocolille Hut Box",
      url: "/images/toffee/COCOILLE ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Cocolille Hut Box",
    },

    {
      name: "Eclair Dark Jar",
      url: "/images/toffee/eclair dark jar 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
    },
    {
      name: "Goa Kaju jar",
      url: "/images/toffee/GOA KAJU 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Goa Kaju jar",
    },
    {
      name: "Eclair Almond Jar",
      url: "/images/toffee/Eclairs Almond  Jar.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
    },
    {
      name: "Eclair Hazelnut",
      url: "/images/toffee/eclair hazelnut 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },
    {
      name: "Eclair Milk",
      url: "/images/toffee/eclair milk 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },
    {
      name: "Eclairs Gold Pouch",
      url: "/images/toffee/ECLAIRS GOLD POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclairs Gold Pouch",
      brand: "gold",
    },
    {
      name: "Goa Almond Jar",
      url: "/images/toffee/GOA ALMOND 2RS.webp",
      price: 2,
      category: "Jar",
      subCategory: "Goa Almond Jar",
    },
    {
      name: "Jewels Pouch",
      url: "/images/toffee/JEWELS POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Jewels Pouch",
    },
    {
      name: "Kaju Butter Hut Box",
      url: "/images/toffee/KAJU BUTTER ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Kaju Butter Hut Box",
    },

    {
      name: "Natural Hut Box",
      url: "/images/toffee/NATURAL ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Natural Hut Box",
    },
    {
      name: "Pista Butter Pouch",
      url: "/images/toffee/PISTA BUTTER POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Pista Butter Pouch",
    },
    {
      name: "Swissdairy Pouch",
      url: "/images/toffee/SWISSDAIRY POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Swissdairy Pouch",
    },
    {
      name: "Anjeer Hut Box",
      url: "/images/toffee/ANJEER ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Anjeer Hut Box",
    },
    {
      name: "Butterscotch Pouch",
      url: "/images/toffee/BUTTERSCOTCH POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Butterscotch Pouch",
    },
    {
      name: "Coconut Butter Pouch",
      url: "/images/toffee/COCONUT BUTTER POUCH R1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Coconut Butter Pouch",
    },

    {
      name: "Eclair Coconut Box",
      url: "/images/toffee/eclair coconut cream gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
    },

    {
      name: "Eclair Hazelnut Gift Box",
      url: "/images/toffee/eclair hazelnut gif box 2RS.webp",
      price: 2,
    },
    {
      name: "Eclair Milk Box",
      url: "/images/toffee/eclair milk gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
    },
    {
      name: "Cocotana Box",
      url: "/images/toffee/Cocotana.webp",
      price: 2,
      category: "Box",
      subCategory: "Cocotana Box ",
    },
    {
      name: "Eclair Milk Jar",
      url: "/images/toffee/eclairs milk jar 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
    },
    {
      name: "Jewels Hut Box",
      url: "/images/toffee/JEWELS ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Jewels Hut Box",
    },
    {
      name: "Kasata Creme Hut Box",
      url: "/images/toffee/KASATA CREME  ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Kasata Creme Hut Box",
    },
    {
      name: "Pan Bites Hut Box",
      url: "/images/toffee/PAN BITES ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Pan Bites Hut Box",
    },
    {
      name: "Pista Harvest",
      url: "/images/toffee/pista harvest 2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Pista Harvest Container",
    },
    {
      name: "Trasure",
      url: "/images/toffee/Trasure 2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Trasure Container",
    },
    {
      name: "Butter Feast Pouch",
      url: "/images/toffee/BUTTER FEAST POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Butter Feast Pouch",
    },
    {
      name: "Caramal Honey",
      url: "/images/toffee/CARAMAL HONEY2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Caramal Honey Container",
    },
    {
      name: "Coconut Butter Hut Box",
      url: "/images/toffee/COCONUT BUTTER ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Coconut Butter Hut Box",
    },
    {
      name: "Eclair Anjeer Cream",
      url: "/images/toffee/eclair anjeer cream 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },

    {
      name: "Eclair Dark Cream",
      url: "/images/toffee/eclair dark cream 2RS.webp",
      price: 2,
      category: "Pouch",
      subCategory: "Eclair Milk",
    },
    {
      name: "Eclair Gold Box",
      url: "/images/toffee/ECLAIR GOLD 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Eclair Gold Box",
      brand: "gold",
    },
    {
      name: "Eclair Hazelnut Jar",
      url: "/images/toffee/eclair hazelnut jar 1RS.webp",
      price: 1,
      category: "Jar",
      subCategory: "Eclair 1rs Jar",
    },

    {
      name: "Eclairs Pouch",
      url: "/images/toffee/ECLAIRS POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclairs Pouch",
    },

    {
      name: "Kesar Cream Hut Box",
      url: "/images/toffee/KESAR CREAM ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Kesar Cream Hut Box",
    },

    {
      name: "Pista Butter Hut Box",
      url: "/images/toffee/PISTA BUTTER BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Pista Butter Hut Box",
    },
    {
      name: "Almond Gold Pouch",
      url: "/images/toffee/ALMOND GOLD POUCH RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Almond Gold Pouch",
      brand: "gold",
    },
    {
      name: "Butter Feast Hut Box",
      url: "/images/toffee/BUTTER FEAST ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Butter Feast Hut Box",
    },
    {
      name: "Choco Almond Grand",
      url: "/images/toffee/CHOCO ALMOND GRAND 2RS.webp",
      price: 2,
      category: "Container",
      subCategory: "Choco Almond Grand Container",
    },
    {
      name: "Dairy Way Hut Box",
      url: "/images/toffee/DAIRY WAY ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Dairy Way Hut Box",
    },
    {
      name: "Eclair Anjeer Box",
      url: "/images/toffee/eclair anjeer cream gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
    },
    {
      name: "Eclair Dark Box",
      url: "/images/toffee/eclair dark cream gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Eclair Box ",
    },

    {
      name: "Eclairs Hut Box",
      url: "/images/toffee/ECLAIRS ZUPADI BOX 1RS.webp",
      price: 1,
      category: "Box",
      subCategory: "Eclairs Hut Box",
    },
    {
      name: "Dry Fruit Selection Box",
      url: "/images/toffee/dry fruit selection gift box 2RS.webp",
      price: 2,
      category: "Box",
      subCategory: "Dry Fruit Selection Box",
    },
    {
      name: "Eclair Dark Pouch",
      url: "/images/toffee/eclair dark pouch 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
    },
    {
      name: "Eclairs Carmallos",
      url: "/images/toffee/eclairs carmallos 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
    },
    {
      name: "Eclair Hazelnut Pouch",
      url: "/images/toffee/eclair hazelnut pouch 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
    },
    {
      name: "Eclair Milk Pouch",
      url: "/images/toffee/eclair milk pouch 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Eclair Dark Pouch",
    },
  ],
  jelly: [
    {
      name: "Jellos Guvava Jelly Jar",
      url: "/images/jelly/JELLOS GUVAVA JELLY JAR.webp",
      price: 1,
    },
    {
      name: "Jellos Guvava Jelly",
      url: "/images/jelly/JELLOS GUVAVA JELLY.webp",
      price: 1,
    },
    {
      name: "Jellos Jelly Jar",
      url: "/images/jelly/JELLOS JELLY JAR.webp",
      price: 1,
    },
    {
      name: "Jellos Jelly Jar1",
      url: "/images/jelly/JELLOS JELLY JAR1.webp",
      price: 1,
    },
    { name: "Jellos Jelly", url: "/images/jelly/JELLOS JELLY.webp", price: 1 },
    {
      name: "Jellos Mango Jelly Jar",
      url: "/images/jelly/JELLOS MANGO JELLY JAR.webp",
      price: 1,
    },
    {
      name: "Jellos Mango Jelly",
      url: "/images/jelly/JELLOS MANGO JELLY.webp",
      price: 1,
    },
    {
      name: "Jellos Mix Fruit Jelly Jar",
      url: "/images/jelly/JELLOS MIX FRUIT JELLY JAR.webp",
      price: 1,
    },
    {
      name: "Jellos Mixfruit Jelly",
      url: "/images/jelly/JELLOS MIXFRUIT JELLY.webp",
      price: 1,
    },
    {
      name: "Jellos Orange Jelly Jar",
      url: "/images/jelly/JELLOS ORANGE JELLY JAR.webp",
      price: 1,
    },
    {
      name: "Jellos Orange Jelly",
      url: "/images/jelly/JELLOS ORANGE JELLY.webp",
      price: 1,
    },
    {
      name: "Jellos Painapple Jelly",
      url: "/images/jelly/JELLOS PAINAPPLE JELLY.webp",
      price: 1,
    },
    {
      name: "Strawberry Jelly Jar",
      url: "/images/jelly/STRAWBERRY JELLY JAR.webp",
      price: 1,
    },
    {
      name: "Strawberry Jelly",
      url: "/images/jelly/STRAWBERRY JELLY.webp",
      price: 1,
    },
  ],
  candy: [
    {
      name: "Double Berry",
      url: "/images/candy/DOUBLE BERRY RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Berry",
    },
    {
      name: "Double Coconut",
      url: "/images/candy/DOUBLE COCONUT RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Coconut",
    },
    {
      name: "Double Kaccha Aam",
      url: "/images/candy/DOUBLE KACCHA AAM RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Kaccha Aam",
    },
    {
      name: "Double Mango",
      url: "/images/candy/DOUBLE MANGO RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Mango",
      brand: "double mango",
    },
    {
      name: "Double Orange",
      url: "/images/candy/DOUBLE ORANGE RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Orange",
    },
    {
      name: "Double Guvava",
      url: "/images/candy/DOUBLE GUVAVA RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Guvava",
    },
    {
      name: "Double Paan",
      url: "/images/candy/DOUBLE PAAN RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Double Paan",
      brand: "double paan",
    },

    {
      name: "Kacha Aam",
      url: "/images/candy/KACHA AAM 50 PAISA.webp",
      price: 0.5,
    },
    {
      name: "Kisszone 165Pcs",
      url: "/images/candy/KISSZONE RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Kisszone 165Pcs",
      brand: "kiss zone",
    },
    {
      name: "Kisszone01",
      url: "/images/candy/KISSZONE01 1RS.webp",
      price: 1,
      brand: "kiss zone",
    },
    {
      name: "Kisszone 50pcs",
      url: "/images/candy/KISSZONE02 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Kisszone 50pcs",
      brand: "kiss zone",
    },
    {
      name: "Beating Heart",
      url: "/images/candy/BEATING HEART RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Beating Heart",
    },
    {
      name: "Kisszone Dark",
      url: "/images/candy/KISSZONE DARK RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Kisszone Dark",
      brand: "kiss zone",
    },
    {
      name: "Pan Meetha",
      url: "/images/candy/PAN MEETHA 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Pan Meetha",
    },
    {
      name: "Tambley",
      url: "/images/candy/TAMBLEY 1RS.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Tambley",
    },
    {
      name: "Kacha Aam Candy",
      url: "/images/candy/KACHA AAM CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "Kacha Aam Candy",
    },
    {
      name: "Londoncow",
      url: "/images/candy/LONDONCOW RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Londoncow",
    },
    {
      name: "Orage",
      url: "/images/candy/ORAGE RS1.webp",
      price: 1,
      category: "Pouch",
      subCategory: "Orage",
    },
    {
      name: "Fruit Bon ",
      url: "/images/candy/FRUIT BON BON 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "Fruit Bon Bon",
    },
    {
      name: "Fruits Candy",
      url: "/images/candy/FRUITS CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
    },
    {
      name: "Imli Candy",
      url: "/images/candy/IMLI CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
    },
    {
      name: "Mango Candy",
      url: "/images/candy/MANGO CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
    },
    {
      name: "Orange Candy",
      url: "/images/candy/ORNGE CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
    },

    {
      name: "Pineapple Candy",
      url: "/images/candy/PINEAPPLE CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
    },
    {
      name: "Strawberry Candy",
      url: "/images/candy/STRAWBERRY CANDY 50 PAISA.webp",
      price: 0.5,
      category: "Pouch",
      subCategory: "China Candy",
    },
    {
      name: "Double Mango ",
      url: "/images/centerMissing/Double Mango .webp",
      price: 0.5,
      category: "Jar",
      subCategory: "Double Mango Jar",
      brand: "double mango",
    },
  ],

  lollipop: [
    {
      name: "Fru Go Pop",
      url: "/images/lollipop/Fru Go Pop.webp",
      price: 5,
    },
    {
      name: "Frudoza",
      url: "/images/lollipop/Frudoza.webp",
      price: 5,
    },
    {
      name: "Frugo Pop Jar",
      url: "/images/lollipop/Frugo Pop Jar.webp",
      price: 5,
    },
    {
      name: "Frugo Pop Pouch",
      url: "/images/lollipop/Frugo Pop Pouch.webp",
      price: 5,
    },
    {
      name: "Frutos Lollipop Jar",
      url: "/images/lollipop/FRUTOS LOLLIPOP JAR.webp",
      price: 5,
    },
    {
      name: "Lolly Lollipop Pouch",
      url: "/images/lollipop/LOLLY LOLLIPOP  POUCH.webp",
      price: 5,
    },
    {
      name: "Lolly Lollipop",
      url: "/images/lollipop/LOLLY LOLLIPOP.webp",
      price: 5,
    },
  ],
};

export default productObj;
